"""QC-2 QPACK cross-validation: decode oracle wire bytes and compare headers.

Oracle vectors: conformance/vectors/rfc9204/qpack_static.json (generated by pylsqpack)

Each test feeds oracle-generated hex bytes to our QpackDecoder and verifies
the decoded headers match. Selected tests also verify our encoder output
matches the oracle byte-for-byte (possible only for fully-indexed fields
where Huffman strategy is irrelevant, and for the name-reference case where
pylsqpack and our encoder use the same encoding).
"""
from src.h3.qpack import QpackDecoder, QpackEncoder, QpackHeaderField
from tests._test_util import assert_true, assert_equal_int


def hex_to_bytes(h: String) raises -> List[UInt8]:
    """Convert a hex string to bytes."""
    if len(h) % 2 != 0:
        raise "hex_to_bytes: odd-length hex string"
    var result = List[UInt8]()
    var bv = h.as_bytes()
    for i in range(0, len(h), 2):
        var hi = bv[i]
        var lo = bv[i + 1]
        var val = Int(0)
        if hi >= 48 and hi <= 57:
            val = (Int(hi) - 48) << 4
        elif hi >= 97 and hi <= 102:
            val = (Int(hi) - 97 + 10) << 4
        elif hi >= 65 and hi <= 70:
            val = (Int(hi) - 65 + 10) << 4
        else:
            raise "hex_to_bytes: invalid hex character"
        if lo >= 48 and lo <= 57:
            val |= Int(lo) - 48
        elif lo >= 97 and lo <= 102:
            val |= Int(lo) - 97 + 10
        elif lo >= 65 and lo <= 70:
            val |= Int(lo) - 65 + 10
        else:
            raise "hex_to_bytes: invalid hex character"
        result.append(UInt8(val))
    return result^


def assert_bytes_equal(actual: List[UInt8], expected: List[UInt8], label: String) raises:
    """Assert two byte sequences are identical."""
    assert_equal_int(len(actual), len(expected), label + " length")
    for i in range(len(expected)):
        assert_equal_int(Int(actual[i]), Int(expected[i]), label + " byte[" + String(i) + "]")


def test_cross_decode_get_slash() raises:
    """Oracle: GET / via indexed static fields (all four headers indexed).
    encoded_hex: 0000d1c1d750882f91d35d055c87a7
    Decode oracle bytes → verify all 4 headers.
    """
    var wire = hex_to_bytes("0000d1c1d750882f91d35d055c87a7")
    var dec = QpackDecoder()
    var headers = dec.decode(wire)
    assert_equal_int(len(headers), 4, "decoded header count")
    assert_true(headers[0].name == ":method", "h0.name")
    assert_true(headers[0].value == "GET", "h0.value")
    assert_true(headers[1].name == ":path", "h1.name")
    assert_true(headers[1].value == "/", "h1.value")
    assert_true(headers[2].name == ":scheme", "h2.name")
    assert_true(headers[2].value == "https", "h2.value")
    assert_true(headers[3].name == ":authority", "h3.name")
    assert_true(headers[3].value == "example.com", "h3.value")
    print("  test_cross_decode_get_slash: PASS")


def test_cross_decode_post_upload() raises:
    """Oracle: POST /upload with content-type (6 headers, mixed indexed + name-ref).
    encoded_hex: 0000d4518562dae838e4d750882f91d35d055c87a7eec4
    Decode oracle bytes → verify all 6 headers.
    """
    var wire = hex_to_bytes("0000d4518562dae838e4d750882f91d35d055c87a7eec4")
    var dec = QpackDecoder()
    var headers = dec.decode(wire)
    assert_equal_int(len(headers), 6, "decoded header count")
    assert_true(headers[0].name == ":method", "h0.name")
    assert_true(headers[0].value == "POST", "h0.value")
    assert_true(headers[1].name == ":path", "h1.name")
    assert_true(headers[1].value == "/upload", "h1.value")
    assert_true(headers[2].name == ":scheme", "h2.name")
    assert_true(headers[2].value == "https", "h2.value")
    assert_true(headers[3].name == ":authority", "h3.name")
    assert_true(headers[3].value == "example.com", "h3.value")
    assert_true(headers[4].name == "content-type", "h4.name")
    assert_true(headers[4].value == "application/json", "h4.value")
    assert_true(headers[5].name == "content-length", "h5.name")
    assert_true(headers[5].value == "0", "h5.value")
    print("  test_cross_decode_post_upload: PASS")


def test_cross_decode_200_ok() raises:
    """Oracle: 200 OK response (3 fully-indexed headers).
    encoded_hex: 0000d9f4e7
    Decode AND encode: fully-indexed means encoder output is deterministic
    regardless of Huffman setting, so we can pin the encode direction too.
    """
    var oracle_hex = "0000d9f4e7"
    # Decode direction
    var wire = hex_to_bytes(oracle_hex)
    var dec = QpackDecoder()
    var headers = dec.decode(wire)
    assert_equal_int(len(headers), 3, "decoded header count")
    assert_true(headers[0].name == ":status", "h0.name")
    assert_true(headers[0].value == "200", "h0.value")
    assert_true(headers[1].name == "content-type", "h1.name")
    assert_true(headers[1].value == "text/html; charset=utf-8", "h1.value")
    assert_true(headers[2].name == "cache-control", "h2.name")
    assert_true(headers[2].value == "no-cache", "h2.value")
    # Encode direction (fully indexed — Huffman irrelevant)
    var enc = QpackEncoder(False)
    var fields = List[QpackHeaderField]()
    fields.append(QpackHeaderField(":status", "200"))
    fields.append(QpackHeaderField("content-type", "text/html; charset=utf-8"))
    fields.append(QpackHeaderField("cache-control", "no-cache"))
    var encoded = enc.encode(fields)
    assert_bytes_equal(encoded, wire, "encode must match oracle")
    print("  test_cross_decode_200_ok: PASS")


def test_cross_decode_404() raises:
    """Oracle: 404 Not Found (1 fully-indexed header).
    encoded_hex: 0000db
    Decode AND encode.
    """
    var oracle_hex = "0000db"
    var wire = hex_to_bytes(oracle_hex)
    var dec = QpackDecoder()
    var headers = dec.decode(wire)
    assert_equal_int(len(headers), 1, "decoded header count")
    assert_true(headers[0].name == ":status", "h0.name")
    assert_true(headers[0].value == "404", "h0.value")
    # Encode direction (fully indexed)
    var enc = QpackEncoder(False)
    var fields = List[QpackHeaderField]()
    fields.append(QpackHeaderField(":status", "404"))
    var encoded = enc.encode(fields)
    assert_bytes_equal(encoded, wire, "encode must match oracle")
    print("  test_cross_decode_404: PASS")


def test_cross_decode_custom_literal() raises:
    """Oracle: :method GET + x-custom-header (§4.5.6 literal without name ref).
    encoded_hex: 0000d12f04f2b12d424f4ad3947216cf86a7d771d1697f
    Decode oracle bytes → verify both headers.
    """
    var wire = hex_to_bytes("0000d12f04f2b12d424f4ad3947216cf86a7d771d1697f")
    var dec = QpackDecoder()
    var headers = dec.decode(wire)
    assert_equal_int(len(headers), 2, "decoded header count")
    assert_true(headers[0].name == ":method", "h0.name")
    assert_true(headers[0].value == "GET", "h0.value")
    assert_true(headers[1].name == "x-custom-header", "h1.name")
    assert_true(headers[1].value == "myvalue", "h1.value")
    print("  test_cross_decode_custom_literal: PASS")


def test_cross_decode_patch_name_ref() raises:
    """Oracle: :method PATCH + :path /api (§4.5.4 literal with name ref).
    encoded_hex: 00005f00055041544348518360759b
    Decode oracle bytes → verify both headers.
    Also verify encoder output for :method PATCH matches oracle's first field
    (use_huffman=False: oracle uses H=0 for PATCH value, matches our literal output).
    """
    var oracle_hex = "00005f00055041544348518360759b"
    # Decode direction
    var wire = hex_to_bytes(oracle_hex)
    var dec = QpackDecoder()
    var headers = dec.decode(wire)
    assert_equal_int(len(headers), 2, "decoded header count")
    assert_true(headers[0].name == ":method", "h0.name")
    assert_true(headers[0].value == "PATCH", "h0.value")
    assert_true(headers[1].name == ":path", "h1.name")
    assert_true(headers[1].value == "/api", "h1.value")
    # Encode direction: verify §4.5.4 header byte and index bytes for :method PATCH
    # (first 10 bytes match oracle exactly for use_huffman=False)
    var enc = QpackEncoder(False)
    var fields = List[QpackHeaderField]()
    fields.append(QpackHeaderField(":method", "PATCH"))
    var encoded = enc.encode(fields)
    assert_equal_int(Int(encoded[2]), 0x5F, "§4.5.4 first byte: N=0 T=1 index=15 multi-byte")
    assert_equal_int(Int(encoded[3]), 0x00, "§4.5.4 second byte: remainder=0")
    assert_equal_int(Int(encoded[4]), 0x05, "value H=0 length=5")
    print("  test_cross_decode_patch_name_ref: PASS")


def test_cross_decode_huffman() raises:
    """Oracle: GET / + :authority www.example.com with Huffman.
    encoded_hex: 0000d1c1d7508cf1e3c2e5f23a6ba0ab90f4ff
    Decode oracle bytes (Huffman value in §4.5.4 field) → verify all 4 headers.
    """
    var wire = hex_to_bytes("0000d1c1d7508cf1e3c2e5f23a6ba0ab90f4ff")
    var dec = QpackDecoder()
    var headers = dec.decode(wire)
    assert_equal_int(len(headers), 4, "decoded header count")
    assert_true(headers[0].name == ":method", "h0.name")
    assert_true(headers[0].value == "GET", "h0.value")
    assert_true(headers[1].name == ":path", "h1.name")
    assert_true(headers[1].value == "/", "h1.value")
    assert_true(headers[2].name == ":scheme", "h2.name")
    assert_true(headers[2].value == "https", "h2.value")
    assert_true(headers[3].name == ":authority", "h3.name")
    assert_true(headers[3].value == "www.example.com", "h3.value")
    print("  test_cross_decode_huffman: PASS")


def main() raises:
    print("=== test_qpack_cross (QC-2) ===")
    test_cross_decode_get_slash()
    test_cross_decode_post_upload()
    test_cross_decode_200_ok()
    test_cross_decode_404()
    test_cross_decode_custom_literal()
    test_cross_decode_patch_name_ref()
    test_cross_decode_huffman()
    print("All QPACK cross-validation tests passed.")
