"""QC-2 QPACK cross-validation: decode oracle wire bytes and compare headers.

Oracle vectors: conformance/vectors/rfc9204/qpack_static.json (generated by pylsqpack)

Each test feeds oracle-generated hex bytes to our QpackDecoder and verifies
the decoded headers match. Selected tests also verify our encoder output
matches the oracle byte-for-byte (possible only for fully-indexed fields
where Huffman strategy is irrelevant, and for the name-reference case where
pylsqpack and our encoder use the same encoding).
"""
from navette.h3.qpack import QpackDecoder, QpackEncoder, FieldSection
from oracle.test_util import assert_true, assert_equal


def hex_to_bytes(h: String) raises -> List[Byte]:
    """Convert a hex string to bytes."""
    if h.byte_length() % 2 != 0:
        raise "hex_to_bytes: odd-length hex string"
    var result = List[Byte]()
    var bv = h.as_bytes()
    for i in range(0, h.byte_length(), 2):
        var hi = bv[i]
        var lo = bv[i + 1]
        var val = Int(0)
        if hi >= 48 and hi <= 57:
            val = (Int(hi) - 48) << 4
        elif hi >= 97 and hi <= 102:
            val = (Int(hi) - 97 + 10) << 4
        elif hi >= 65 and hi <= 70:
            val = (Int(hi) - 65 + 10) << 4
        else:
            raise "hex_to_bytes: invalid hex character"
        if lo >= 48 and lo <= 57:
            val |= Int(lo) - 48
        elif lo >= 97 and lo <= 102:
            val |= Int(lo) - 97 + 10
        elif lo >= 65 and lo <= 70:
            val |= Int(lo) - 65 + 10
        else:
            raise "hex_to_bytes: invalid hex character"
        result.append(UInt8(val))
    return result^


def assert_bytes_equal(actual: List[Byte], expected: List[Byte], label: String) raises:
    """Assert two byte sequences are identical."""
    assert_equal(len(actual), len(expected), label + " length")
    for i in range(len(expected)):
        assert_equal(Int(actual[i]), Int(expected[i]), label + " byte[" + String(i) + "]")


def test_cross_decode_get_slash() raises:
    """Oracle: GET / via indexed static fields (all four headers indexed).
    encoded_hex: 0000d1c1d750882f91d35d055c87a7
    Decode oracle bytes → verify all 4 headers.
    """
    var wire = hex_to_bytes("0000d1c1d750882f91d35d055c87a7")
    var dec = QpackDecoder()
    var section = dec.decode(wire)
    assert_equal(len(section.headers), 0, "no regular fields")
    assert_true(section.method == "GET", ":method")
    assert_true(section.path == "/", ":path")
    assert_true(section.scheme == "https", ":scheme")
    assert_true(section.authority == "example.com", ":authority")
    print("  test_cross_decode_get_slash: PASS")


def test_cross_decode_post_upload() raises:
    """Oracle: POST /upload with content-type (6 headers, mixed indexed + name-ref).
    encoded_hex: 0000d4518562dae838e4d750882f91d35d055c87a7eec4
    Decode oracle bytes → verify all 6 headers.
    """
    var wire = hex_to_bytes("0000d4518562dae838e4d750882f91d35d055c87a7eec4")
    var dec = QpackDecoder()
    var section = dec.decode(wire)
    assert_true(section.method == "POST", ":method")
    assert_true(section.path == "/upload", ":path")
    assert_true(section.scheme == "https", ":scheme")
    assert_true(section.authority == "example.com", ":authority")
    ref headers = section.headers
    assert_equal(len(headers), 2, "regular field count")
    assert_true(headers.name_at(0) == "content-type", "h0.name")
    assert_true(headers.value_at(0) == "application/json", "h0.value")
    assert_true(headers.name_at(1) == "content-length", "h1.name")
    assert_true(headers.value_at(1) == "0", "h1.value")
    print("  test_cross_decode_post_upload: PASS")


def test_cross_decode_200_ok() raises:
    """Oracle: 200 OK response (3 fully-indexed headers).
    encoded_hex: 0000d9f4e7
    Decode AND encode: fully-indexed means encoder output is deterministic
    regardless of Huffman setting, so we can pin the encode direction too.
    """
    var oracle_hex = "0000d9f4e7"
    # Decode direction
    var wire = hex_to_bytes(oracle_hex)
    var dec = QpackDecoder()
    var section = dec.decode(wire)
    assert_true(section.status == "200", ":status")
    ref headers = section.headers
    assert_equal(len(headers), 2, "regular field count")
    assert_true(headers.name_at(0) == "content-type", "h0.name")
    assert_true(headers.value_at(0) == "text/html; charset=utf-8", "h0.value")
    assert_true(headers.name_at(1) == "cache-control", "h1.name")
    assert_true(headers.value_at(1) == "no-cache", "h1.value")
    # Encode direction (fully indexed — Huffman irrelevant)
    var enc = QpackEncoder(False)
    var encoded = List[Byte]()
    enc.encode(encoded, section)
    assert_bytes_equal(encoded, wire, "encode must match oracle")
    print("  test_cross_decode_200_ok: PASS")


def test_cross_decode_404() raises:
    """Oracle: 404 Not Found (1 fully-indexed header).
    encoded_hex: 0000db
    Decode AND encode.
    """
    var oracle_hex = "0000db"
    var wire = hex_to_bytes(oracle_hex)
    var dec = QpackDecoder()
    var section = dec.decode(wire)
    assert_true(section.status == "404", ":status")
    assert_equal(len(section.headers), 0, "no regular fields")
    # Encode direction (fully indexed)
    var enc = QpackEncoder(False)
    var encoded = List[Byte]()
    enc.encode(encoded, FieldSection(status="404"))
    assert_bytes_equal(encoded, wire, "encode must match oracle")
    print("  test_cross_decode_404: PASS")


def test_cross_decode_custom_literal() raises:
    """Oracle: :method GET + x-custom-header (§4.5.6 literal without name ref).
    encoded_hex: 0000d12f04f2b12d424f4ad3947216cf86a7d771d1697f
    Decode oracle bytes → verify both headers.
    """
    var wire = hex_to_bytes("0000d12f04f2b12d424f4ad3947216cf86a7d771d1697f")
    var dec = QpackDecoder()
    var section = dec.decode(wire)
    assert_true(section.method == "GET", ":method")
    assert_equal(len(section.headers), 1, "regular field count")
    assert_true(section.headers.name_at(0) == "x-custom-header", "h0.name")
    assert_true(section.headers.value_at(0) == "myvalue", "h0.value")
    print("  test_cross_decode_custom_literal: PASS")


def test_cross_decode_patch_name_ref() raises:
    """Oracle: :method PATCH + :path /api (RFC 9204 sec 4.5.4 literal with name ref).
    encoded_hex: 00005f00055041544348518360759b
    Decode oracle bytes → verify both headers.
    Also verify encoder output for :method PATCH matches oracle's first field
    (use_huffman=False: oracle uses H=0 for PATCH value, matches our literal output).
    """
    var oracle_hex = "00005f00055041544348518360759b"
    # Decode direction
    var wire = hex_to_bytes(oracle_hex)
    var dec = QpackDecoder()
    var section = dec.decode(wire)
    assert_true(section.method == "PATCH", ":method")
    assert_true(section.path == "/api", ":path")
    assert_equal(len(section.headers), 0, "no regular fields")
    # Encode direction: verify RFC 9204 sec 4.5.4 header byte and index bytes for :method PATCH
    # (first 10 bytes match oracle exactly for use_huffman=False)
    var enc = QpackEncoder(False)
    var encoded = List[Byte]()
    enc.encode(encoded, FieldSection(method="PATCH"))
    assert_equal(Int(encoded[2]), 0x5F, "RFC 9204 sec 4.5.4 first byte: N=0 T=1 index=15 multi-byte")
    assert_equal(Int(encoded[3]), 0x00, "RFC 9204 sec 4.5.4 second byte: remainder=0")
    assert_equal(Int(encoded[4]), 0x05, "value H=0 length=5")
    print("  test_cross_decode_patch_name_ref: PASS")


def test_cross_decode_huffman() raises:
    """Oracle: GET / + :authority www.example.com with Huffman.
    encoded_hex: 0000d1c1d7508cf1e3c2e5f23a6ba0ab90f4ff
    Decode oracle bytes (Huffman value in RFC 9204 sec 4.5.4 field) → verify all 4 headers.
    """
    var wire = hex_to_bytes("0000d1c1d7508cf1e3c2e5f23a6ba0ab90f4ff")
    var dec = QpackDecoder()
    var section = dec.decode(wire)
    assert_true(section.method == "GET", ":method")
    assert_true(section.path == "/", ":path")
    assert_true(section.scheme == "https", ":scheme")
    assert_true(section.authority == "www.example.com", ":authority")
    assert_equal(len(section.headers), 0, "no regular fields")
    print("  test_cross_decode_huffman: PASS")


def main() raises:
    print("=== test_qpack_cross (QC-2) ===")
    test_cross_decode_get_slash()
    test_cross_decode_post_upload()
    test_cross_decode_200_ok()
    test_cross_decode_404()
    test_cross_decode_custom_literal()
    test_cross_decode_patch_name_ref()
    test_cross_decode_huffman()
    print("All QPACK cross-validation tests passed.")
