# conformance/tests/test_cross_initial_crypto.mojo
#
# Cross-validation test: derives QUIC v1 Initial keys using aioquic's
# native crypto functions AND librustls_mojo.so, asserting both produce
# identical keys and both match the pre-materialized expected values
# from the RFC 9001 A.1 oracle vectors.
#
# As of §3.2 of plans/2026-05-13-deps-enhancement.md, this test no longer
# imports `cryptography.hazmat` at runtime. The "our cryptography path"
# (formerly Path A) has been removed; the trusted oracle is the JSON
# fixture conformance/vectors/rfc9001/initial_keys.json, generated by
# conformance/scripts/oracle_initial.py.
#
# Path B (aioquic) is still imported at test time and is the subject of
# §3.3 (aioquic pre-materialization). Path C (rustls FFI) is the
# system-under-test.
from lib.test_util import load_vectors, assert_true, hex_decode, hex_encode
from lib.rustls import RustlsLibrary
from std.memory.unsafe_pointer import alloc as _heap_alloc
from python import Python, PythonObject


fn py_bytes_to_hex(raw: PythonObject) raises -> String:
    """Convert a Python bytes object to a lowercase hex string."""
    var binascii = Python.import_module("binascii")
    return String(binascii.hexlify(raw).decode("ascii"))


def rustls_derive_keys(
    lib: RustlsLibrary,
    dcid_hex: String,
    is_client: Int32,
) raises -> List[String]:
    """Derive key, iv, hp via librustls_mojo.so. Returns list [key, iv, hp] as hex strings."""
    var dcid_bytes = hex_decode(dcid_hex)
    var dcid_ptr = _heap_alloc[UInt8](len(dcid_bytes)).as_any_origin()
    for i in range(len(dcid_bytes)):
        dcid_ptr[i] = dcid_bytes[i]

    var out_key = _heap_alloc[UInt8](32).as_any_origin()
    var out_iv = _heap_alloc[UInt8](12).as_any_origin()
    var out_hp = _heap_alloc[UInt8](32).as_any_origin()
    var out_key_len = _heap_alloc[Int32](1).as_any_origin()
    var out_iv_len = _heap_alloc[Int32](1).as_any_origin()
    var out_hp_len = _heap_alloc[Int32](1).as_any_origin()
    # rlsm_initial_keys_raw treats *out_*_len as in/out: caller writes capacity.
    out_key_len[] = Int32(32)
    out_iv_len[] = Int32(12)
    out_hp_len[] = Int32(32)

    var rc = lib.initial_keys_raw(
        Int32(1),  # QUIC v1
        dcid_ptr,
        Int32(len(dcid_bytes)),
        is_client,
        out_key, out_key_len,
        out_iv, out_iv_len,
        out_hp, out_hp_len,
    )
    assert_true(
        Int(rc) == 0,
        "rustls rlsm_initial_keys_raw failed: " + lib.last_error(),
    )

    var key_list = List[UInt8]()
    for i in range(Int(out_key_len[])):
        key_list.append(out_key[i])
    var iv_list = List[UInt8]()
    for i in range(Int(out_iv_len[])):
        iv_list.append(out_iv[i])
    var hp_list = List[UInt8]()
    for i in range(Int(out_hp_len[])):
        hp_list.append(out_hp[i])

    var key_hex = hex_encode(key_list)
    var iv_hex = hex_encode(iv_list)
    var hp_hex = hex_encode(hp_list)

    dcid_ptr.free()
    out_key.free()
    out_iv.free()
    out_hp.free()
    out_key_len.free()
    out_iv_len.free()
    out_hp_len.free()

    var result = List[String]()
    result.append(key_hex)
    result.append(iv_hex)
    result.append(hp_hex)
    return result^


def _find_role_vector(vectors: PythonObject, role: String) raises -> PythonObject:
    """Return the initial_keys.json record matching role ("client" or "server")."""
    var n = Int(py=len(vectors))
    for i in range(n):
        var v = vectors[i]
        if String(v["role"]) == role:
            return v
    raise "initial_keys.json missing role=" + role


def test_key_derivation_cross(
    v_client: PythonObject, v_server: PythonObject, lib: RustlsLibrary
) raises -> None:
    """Cross-validate key derivation: aioquic vs rustls, both vs JSON expected.

    The JSON fixture (initial_keys.json) is the trusted oracle. We assert:
        - aioquic's derivation matches the fixture.
        - rustls (via FFI) matches the fixture.
    Transitively this also asserts aioquic matches rustls.
    """
    var dcid_hex = String(v_client["cid"])
    # Sanity: client and server share the same dcid + initial_secret.
    assert_true(
        String(v_server["cid"]) == dcid_hex,
        "client/server vector dcid mismatch",
    )

    # Expected values (from JSON fixture — trusted oracle).
    var exp_client_key = String(v_client["key"])
    var exp_client_iv  = String(v_client["iv"])
    var exp_client_hp  = String(v_client["hp"])
    var exp_server_key = String(v_server["key"])
    var exp_server_iv  = String(v_server["iv"])
    var exp_server_hp  = String(v_server["hp"])

    # ── Path B: aioquic's native crypto functions ───────────────────────────
    # We obtain the SHA256 hash-algorithm instance via aioquic's
    # `cipher_suite_hash(INITIAL_CIPHER_SUITE)` helper, which avoids
    # importing `cryptography.hazmat` here at test time. (aioquic itself
    # still depends on cryptography, but that is §3.3 territory.)
    var aioquic_crypto = Python.import_module("aioquic.quic.crypto")
    var hkdf_extract = aioquic_crypto.hkdf_extract
    var hkdf_expand_label_aio = aioquic_crypto.hkdf_expand_label
    var derive_key_iv_hp = aioquic_crypto.derive_key_iv_hp
    var cipher_suite_hash = aioquic_crypto.cipher_suite_hash
    var INITIAL_CIPHER_SUITE = aioquic_crypto.INITIAL_CIPHER_SUITE
    var INITIAL_SALT_VERSION_1 = aioquic_crypto.INITIAL_SALT_VERSION_1

    var binascii = Python.import_module("binascii")
    var dcid = binascii.unhexlify(dcid_hex)

    var algorithm = cipher_suite_hash(INITIAL_CIPHER_SUITE)
    var aio_initial_secret = hkdf_extract(algorithm, INITIAL_SALT_VERSION_1, dcid)

    var builtins = Python.import_module("builtins")
    var py_empty = builtins.bytes()
    var aio_client_secret = hkdf_expand_label_aio(
        cipher_suite_hash(INITIAL_CIPHER_SUITE),
        aio_initial_secret,
        builtins.str("client in").encode("ascii"),
        py_empty,
        32,
    )
    var aio_client_tuple = derive_key_iv_hp(
        cipher_suite=INITIAL_CIPHER_SUITE, secret=aio_client_secret, version=1
    )
    var aio_client_key = py_bytes_to_hex(aio_client_tuple[0])
    var aio_client_iv  = py_bytes_to_hex(aio_client_tuple[1])
    var aio_client_hp  = py_bytes_to_hex(aio_client_tuple[2])

    var aio_server_secret = hkdf_expand_label_aio(
        cipher_suite_hash(INITIAL_CIPHER_SUITE),
        aio_initial_secret,
        builtins.str("server in").encode("ascii"),
        py_empty,
        32,
    )
    var aio_server_tuple = derive_key_iv_hp(
        cipher_suite=INITIAL_CIPHER_SUITE, secret=aio_server_secret, version=1
    )
    var aio_server_key = py_bytes_to_hex(aio_server_tuple[0])
    var aio_server_iv  = py_bytes_to_hex(aio_server_tuple[1])
    var aio_server_hp  = py_bytes_to_hex(aio_server_tuple[2])

    # ── Path C: rustls via librustls_mojo.so ───────────────────────────
    var rustls_client = rustls_derive_keys(lib, dcid_hex, Int32(1))
    var rustls_client_key = rustls_client[0]
    var rustls_client_iv  = rustls_client[1]
    var rustls_client_hp  = rustls_client[2]
    var rustls_server = rustls_derive_keys(lib, dcid_hex, Int32(0))
    var rustls_server_key = rustls_server[0]
    var rustls_server_iv  = rustls_server[1]
    var rustls_server_hp  = rustls_server[2]

    # ── Assert aioquic (Path B) matches the JSON oracle ────────────────
    assert_true(aio_client_key == exp_client_key, "client_key: aioquic vs expected mismatch")
    assert_true(aio_client_iv  == exp_client_iv,  "client_iv: aioquic vs expected mismatch")
    assert_true(aio_client_hp  == exp_client_hp,  "client_hp: aioquic vs expected mismatch")
    assert_true(aio_server_key == exp_server_key, "server_key: aioquic vs expected mismatch")
    assert_true(aio_server_iv  == exp_server_iv,  "server_iv: aioquic vs expected mismatch")
    assert_true(aio_server_hp  == exp_server_hp,  "server_hp: aioquic vs expected mismatch")

    # ── Assert rustls (Path C) matches the JSON oracle ─────────────────
    assert_true(rustls_client_key == exp_client_key, "client_key: rustls vs expected mismatch")
    assert_true(rustls_client_iv  == exp_client_iv,  "client_iv: rustls vs expected mismatch")
    assert_true(rustls_client_hp  == exp_client_hp,  "client_hp: rustls vs expected mismatch")
    assert_true(rustls_server_key == exp_server_key, "server_key: rustls vs expected mismatch")
    assert_true(rustls_server_iv  == exp_server_iv,  "server_iv: rustls vs expected mismatch")
    assert_true(rustls_server_hp  == exp_server_hp,  "server_hp: rustls vs expected mismatch")


def main() raises:
    # Verify assertions are working (guard against silent no-op)
    var _sentinel_ok = False
    try:
        assert_true(False, "sentinel")
    except:
        _sentinel_ok = True
    assert_true(_sentinel_ok, "assertions are not firing — test infrastructure is broken")

    var lib = RustlsLibrary()

    var vectors = load_vectors("vectors/rfc9001/initial_keys.json")
    var n = Int(py=len(vectors))
    assert_true(
        n >= 2,
        "expected at least 2 initial_keys vectors (client + server), got " + String(n),
    )

    # Each "vector pair" (client + server with shared dcid) gets cross-validated.
    var v_client = _find_role_vector(vectors, String("client"))
    var v_server = _find_role_vector(vectors, String("server"))

    test_key_derivation_cross(v_client, v_server, lib)

    _ = lib^
    print("test_cross_initial_crypto: aioquic + rustls keys cross-validated against JSON oracle")
