"""Smoke test for H2TcpServer bootstrap (proactor model).

Doesn't require an external HTTP/2 client: spins the proactor lifecycle
through wire_context() + start() + one non-blocking tick + reap_closed(),
and exits. Catches regressions in:

  * H2TcpServer construction (field init order, accept Completion wiring)
  * Completion wiring (wire_context sets accept callback context pointer)
  * start() SQE sequence (initial accept submission on listener fd)
  * one tick cycle (non-blocking — no client connects, accept stays pending)
  * reap_closed() (no-op on empty connection list, verifies no crash)

Cert + key paths default to `certs/server.crt` / `certs/server.key`
(generated by `scripts/gen_test_certs.sh`).
"""

from std.memory import UnsafePointer, Span
from std.memory.unsafe_pointer import alloc as _heap_alloc

from boucle.drivers.io_uring import IoUringDriver

from navette.h2.h2_tcp_server import H2TcpServer
from navette.http.handler import (
    StreamHandler,
    Request,
    RecvBody,
    ResponseWriter,
    Capabilities,
    StreamError,
)
from navette.runtime.socket_helpers import tcp_listener
from navette.tls import TlsBackend, TlsServerConfig

from interop.file_io import read_file


# Stub handler — the smoke test never reaches a request, so all five
# StreamHandler methods are `pass`.
struct StubHandler(StreamHandler):
    """No-op handler for the bootstrap smoke test."""

    def __init__(out self):
        pass

    def __init__(out self, *, deinit take: Self):
        pass

    def on_request(
        mut self, var req: Request, mut body: RecvBody,
        mut resp: ResponseWriter, caps: Capabilities,
    ) raises:
        pass

    def on_body_available(
        mut self, mut body: RecvBody, mut resp: ResponseWriter,
    ) raises:
        pass

    def on_request_end(
        mut self, mut body: RecvBody, mut resp: ResponseWriter,
    ) raises:
        pass

    def on_send_drained(mut self, mut resp: ResponseWriter) raises:
        pass

    def on_reset(mut self, error: StreamError):
        pass


def make_stub_handler() raises -> StubHandler:
    """Per-conn factory handed to H2TcpServer."""
    return StubHandler()


def test_h2_tcp_server_init_and_tick() raises:
    """Spin the server through the full proactor lifecycle.

    Exercises wire_context + start (initial accept submission on the
    listener fd), one non-blocking tick (no client connects, so the
    accept stays pending and tick returns immediately), and reap_closed
    (no-op on empty connection list) — without requiring a real HTTP/2
    client.
    """
    # -- 1. TLS setup --
    var cert = read_file(String("certs/server.crt"))
    var key = read_file(String("certs/server.key"))
    var tls = TlsBackend()
    var config = TlsServerConfig(tls.shared(), Span(cert), Span(key))

    # -- 2. TCP listener on ephemeral port --
    var sock = tcp_listener(0)  # kernel picks a free port
    print("test_h2_tcp_server: bound fd =", Int(sock.raw()))

    # -- 3. Server construction --
    var server = H2TcpServer[StubHandler](
        listen_handle=sock^,
        make_handler=make_stub_handler,
        tls=tls^,
        server_tls_config=config^,
    )

    # -- 4. Heap-allocate for pointer stability --
    var srv_ptr = _heap_alloc[H2TcpServer[StubHandler]](1)
    srv_ptr.init_pointee_move(server^)

    # -- 5. Wire Completion context pointers --
    srv_ptr[].wire_context()

    # -- 6. IoUringDriver + start (initial accept submission) --
    var driver = IoUringDriver(sq_entries=64)
    srv_ptr[].start(driver)

    # -- 7. One non-blocking tick — no client, accept stays pending --
    driver.tick(wait=False)

    # -- 8. Reap closed — no-op on empty connection list --
    srv_ptr[].reap_closed()

    # -- 9. Teardown --
    srv_ptr.destroy_pointee()
    srv_ptr.free()

    print("PASS: test_h2_tcp_server_init_and_tick")


def main() raises:
    test_h2_tcp_server_init_and_tick()
