# conformance/lib/http2/__init__.mojo
# Re-exports from src.h2 + local oracles.
from src.h2.frame import (
    H2_NO_ERROR,
    H2_PROTOCOL_ERROR,
    H2_INTERNAL_ERROR,
    H2_FLOW_CONTROL_ERROR,
    H2_SETTINGS_TIMEOUT,
    H2_STREAM_CLOSED,
    H2_FRAME_SIZE_ERROR,
    H2_REFUSED_STREAM,
    H2_CANCEL,
    H2_COMPRESSION_ERROR,
    H2_CONNECT_ERROR,
    H2_ENHANCE_YOUR_CALM,
    H2_INADEQUATE_SECURITY,
    H2_HTTP_1_1_REQUIRED,
    SCOPE_NONE,
    SCOPE_STREAM,
    SCOPE_CONNECTION,
    FRAME_DATA,
    FRAME_HEADERS,
    FRAME_PRIORITY,
    FRAME_RST_STREAM,
    FRAME_SETTINGS,
    FRAME_PUSH_PROMISE,
    FRAME_PING,
    FRAME_GOAWAY,
    FRAME_WINDOW_UPDATE,
    FRAME_CONTINUATION,
    FLAG_END_STREAM,
    FLAG_ACK,
    FLAG_END_HEADERS,
    FLAG_PADDED,
    FLAG_PRIORITY,
    H2FrameConfig,
    h2_strict_config,
    h2_lenient_config,
    h2_permissive_config,
    Frame,
    decode_frame,
    encode_frame,
)
from src.h2.hpack import HpackEncoder, HpackDecoder, HpackConfig
from src.h2.hpack_huffman import HuffmanCodec
from src.h2.hpack_integer import encode_integer, decode_integer
from src.h2.hpack_table import StaticTable, DynamicTable
from .oracles import h2_roundtrip
# Note: the bulk of the live h2 / hpack / hyperframe oracle wrappers were
# pruned as of deps-enhancement §3.3. Only `h2_roundtrip` remains, used by
# tests/test_h2_stream.mojo. See conformance/scripts/oracle_h1_h2_states.py
# for the pre-materialization pipeline that replaced the others.
from src.h2.payloads import (
    DataPayload,
    decode_data_payload,
    HeadersPayload,
    decode_headers_payload,
    PriorityPayload,
    decode_priority_payload,
    RstStreamPayload,
    decode_rst_stream_payload,
    Setting,
    SettingsPayload,
    decode_settings_payload,
    PushPromisePayload,
    decode_push_promise_payload,
    PingPayload,
    decode_ping_payload,
    GoawayPayload,
    decode_goaway_payload,
    WindowUpdatePayload,
    decode_window_update_payload,
    ContinuationPayload,
    decode_continuation_payload,
)
from src.h2.connection import (
    H2Config,
    H2Settings,
    H2Event,
    StreamState,
    H2Connection,
    H2_EVT_REQUEST_RECEIVED,
    H2_EVT_RESPONSE_RECEIVED,
    H2_EVT_DATA_RECEIVED,
    H2_EVT_TRAILERS_RECEIVED,
    H2_EVT_STREAM_ENDED,
    H2_EVT_STREAM_RESET,
    H2_EVT_SETTINGS_ACKNOWLEDGED,
    H2_EVT_PING_RECEIVED,
    H2_EVT_PING_ACKNOWLEDGED,
    H2_EVT_GOAWAY_RECEIVED,
    H2_EVT_WINDOW_UPDATED,
    H2_EVT_CONNECTION_TERMINATED,
    H2_EVT_SETTINGS_CHANGED,
    CONN_IDLE,
    CONN_OPEN,
    CONN_GOAWAY,
    CONN_CLOSED,
    STREAM_IDLE,
    STREAM_OPEN,
    STREAM_HALF_CLOSED_LOCAL,
    STREAM_HALF_CLOSED_REMOTE,
    STREAM_CLOSED,
    SETTINGS_HEADER_TABLE_SIZE,
    SETTINGS_ENABLE_PUSH,
    SETTINGS_MAX_CONCURRENT_STREAMS,
    SETTINGS_INITIAL_WINDOW_SIZE,
    SETTINGS_MAX_FRAME_SIZE,
    SETTINGS_MAX_HEADER_LIST_SIZE,
    SETTINGS_ENABLE_CONNECT_PROTOCOL,
)
