# AUTO-GENERATED by scripts/gen_ffi_bindings.py - DO NOT EDIT BY HAND.
# Source of truth: crates/libcompress-mojo/symbols.toml.
# Regenerate via: uv run python scripts/gen_ffi_bindings.py --schema crates/libcompress-mojo/symbols.toml --out navette/compress/_lcm_bindings.mojo

from std.ffi import OwnedDLHandle
from std.memory import UnsafePointer


# -- Function-pointer aliases ----------------------------------------------

comptime lcm_last_error_fn = def(UnsafePointer[UInt8, MutAnyOrigin], Int32) abi("C") thin -> Int32
comptime lcm_gzip_init_fn = def(UInt64, UInt64, UInt32) abi("C") thin -> UnsafePointer[NoneType, MutAnyOrigin]
comptime lcm_gzip_feed_fn = def(UnsafePointer[NoneType, MutAnyOrigin], UnsafePointer[UInt8, MutAnyOrigin], Int, UnsafePointer[UInt8, MutAnyOrigin], Int) abi("C") thin -> Int64
comptime lcm_gzip_finish_fn = def(UnsafePointer[NoneType, MutAnyOrigin], UnsafePointer[UInt8, MutAnyOrigin], Int) abi("C") thin -> Int64
comptime lcm_gzip_free_fn = def(UnsafePointer[NoneType, MutAnyOrigin]) abi("C") thin -> None
comptime lcm_br_init_fn = def(UInt64, UInt64, UInt32) abi("C") thin -> UnsafePointer[NoneType, MutAnyOrigin]
comptime lcm_br_feed_fn = def(UnsafePointer[NoneType, MutAnyOrigin], UnsafePointer[UInt8, MutAnyOrigin], Int, UnsafePointer[UInt8, MutAnyOrigin], Int) abi("C") thin -> Int64
comptime lcm_br_finish_fn = def(UnsafePointer[NoneType, MutAnyOrigin], UnsafePointer[UInt8, MutAnyOrigin], Int) abi("C") thin -> Int64
comptime lcm_br_free_fn = def(UnsafePointer[NoneType, MutAnyOrigin]) abi("C") thin -> None

# -- Loader helpers --------------------------------------------------------

# Copy the last libcompress-mojo error message into out_buf (NUL-terminated).
def load_lcm_last_error(ref handle: OwnedDLHandle) -> lcm_last_error_fn:
    return handle.get_function[lcm_last_error_fn]("lcm_last_error")

# Allocate a GzipState with explicit decompression caps. Cap of 0 disables the corresponding check.
def load_lcm_gzip_init(ref handle: OwnedDLHandle) -> lcm_gzip_init_fn:
    return handle.get_function[lcm_gzip_init_fn]("lcm_gzip_init")

# Feed compressed bytes; write up to out_cap decompressed bytes. Returns bytes written (>=0) or -1 (error) / -2 (input cap) / -3 (output cap) / -4 (ratio cap).
def load_lcm_gzip_feed(ref handle: OwnedDLHandle) -> lcm_gzip_feed_fn:
    return handle.get_function[lcm_gzip_feed_fn]("lcm_gzip_feed")

# Drain remaining decompressed bytes. Repeatable until it returns 0.
def load_lcm_gzip_finish(ref handle: OwnedDLHandle) -> lcm_gzip_finish_fn:
    return handle.get_function[lcm_gzip_finish_fn]("lcm_gzip_finish")

# Free a GzipState previously returned by lcm_gzip_init.
def load_lcm_gzip_free(ref handle: OwnedDLHandle) -> lcm_gzip_free_fn:
    return handle.get_function[lcm_gzip_free_fn]("lcm_gzip_free")

# Allocate a BrotliState with explicit decompression caps. Cap of 0 disables the corresponding check.
def load_lcm_br_init(ref handle: OwnedDLHandle) -> lcm_br_init_fn:
    return handle.get_function[lcm_br_init_fn]("lcm_br_init")

# Feed compressed bytes; write up to out_cap decompressed bytes. Same return contract as lcm_gzip_feed.
def load_lcm_br_feed(ref handle: OwnedDLHandle) -> lcm_br_feed_fn:
    return handle.get_function[lcm_br_feed_fn]("lcm_br_feed")

# Drain remaining decompressed bytes. Repeatable until it returns 0.
def load_lcm_br_finish(ref handle: OwnedDLHandle) -> lcm_br_finish_fn:
    return handle.get_function[lcm_br_finish_fn]("lcm_br_finish")

# Free a BrotliState previously returned by lcm_br_init.
def load_lcm_br_free(ref handle: OwnedDLHandle) -> lcm_br_free_fn:
    return handle.get_function[lcm_br_free_fn]("lcm_br_free")
