# AUTO-GENERATED by scripts/gen_ffi_bindings.py - DO NOT EDIT BY HAND.
# Source of truth: crates/libcompress-mojo/symbols.toml.
# Regenerate via: uv run python scripts/gen_ffi_bindings.py --schema crates/libcompress-mojo/symbols.toml --out navette/compress/_lcm_bindings.mojo
#
# Three declarations per symbol:
#
#   <name>_fn     the C ABI, spelled in full. The single place the
#                 argument types are written down.
#   call_<name>   the default call form. Public `get_function[<ret>]`,
#                 so the returned callable borrows the handle and the
#                 library cannot be unloaded mid-call. Its own signature
#                 carries the argument types, which `get_function` no
#                 longer does.
#   load_<name>   a raw C ABI function pointer, for a hot path that must
#                 cache the pointer instead of resolving per call. Not
#                 origin-bound: keeping the owning handle alive for as
#                 long as the pointer is the caller's job.
#
# Either call form fails to compile when the schema and the call
# disagree, so drift surfaces as a build error rather than a corrupted
# stack at runtime.

from std.ffi import OwnedDLHandle
from std.memory import Pointer


# -- C ABI function-pointer aliases ----------------------------------------

comptime lcm_last_error_fn = def(Pointer[UInt8, MutUntrackedOrigin], Int32) abi("C") thin -> Int32
comptime lcm_gzip_init_fn = def(UInt64, UInt64, UInt32) abi("C") thin -> Pointer[NoneType, MutUntrackedOrigin]
comptime lcm_gzip_feed_fn = def(Pointer[NoneType, MutUntrackedOrigin], Pointer[UInt8, MutUntrackedOrigin], Int, Pointer[UInt8, MutUntrackedOrigin], Int) abi("C") thin -> Int64
comptime lcm_gzip_finish_fn = def(Pointer[NoneType, MutUntrackedOrigin], Pointer[UInt8, MutUntrackedOrigin], Int) abi("C") thin -> Int64
comptime lcm_gzip_free_fn = def(Pointer[NoneType, MutUntrackedOrigin]) abi("C") thin -> NoneType
comptime lcm_br_init_fn = def(UInt64, UInt64, UInt32) abi("C") thin -> Pointer[NoneType, MutUntrackedOrigin]
comptime lcm_br_feed_fn = def(Pointer[NoneType, MutUntrackedOrigin], Pointer[UInt8, MutUntrackedOrigin], Int, Pointer[UInt8, MutUntrackedOrigin], Int) abi("C") thin -> Int64
comptime lcm_br_finish_fn = def(Pointer[NoneType, MutUntrackedOrigin], Pointer[UInt8, MutUntrackedOrigin], Int) abi("C") thin -> Int64
comptime lcm_br_free_fn = def(Pointer[NoneType, MutUntrackedOrigin]) abi("C") thin -> NoneType

# -- Typed call wrappers ---------------------------------------------------

@always_inline
def call_lcm_last_error(
    ref lib: OwnedDLHandle,
    out_buf: Pointer[mut=True, T=UInt8, origin=_],
    buf_len: Int32,
) raises -> Int32:
    """Copy the last libcompress-mojo error message into out_buf (NUL-terminated).

    Args:
        lib: An open handle to libcompress_mojo.so.
        out_buf: C `*mut u8`.
        buf_len: C `i32`.

    Returns:
        C `i32`.

    Raises:
        If `lcm_last_error` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("lcm_last_error")(out_buf, buf_len)


@always_inline
def call_lcm_gzip_init(
    ref lib: OwnedDLHandle,
    input_cap: UInt64,
    output_cap: UInt64,
    ratio_x100: UInt32,
) raises -> Pointer[NoneType, MutUntrackedOrigin]:
    """Allocate a GzipState with explicit decompression caps. Cap of 0 disables the corresponding check.

    Args:
        lib: An open handle to libcompress_mojo.so.
        input_cap: C `u64`.
        output_cap: C `u64`.
        ratio_x100: C `u32`.

    Returns:
        C `*mut GzipState`.

    Raises:
        If `lcm_gzip_init` is not exported by the loaded library.
    """
    return lib.get_function[Pointer[NoneType, MutUntrackedOrigin]]("lcm_gzip_init")(input_cap, output_cap, ratio_x100)


@always_inline
def call_lcm_gzip_feed(
    ref lib: OwnedDLHandle,
    state: Pointer[mut=True, T=NoneType, origin=_],
    in_ptr: Pointer[mut=True, T=UInt8, origin=_],
    in_len: Int,
    out_ptr: Pointer[mut=True, T=UInt8, origin=_],
    out_cap: Int,
) raises -> Int64:
    """Feed compressed bytes; write up to out_cap decompressed bytes. Returns bytes written (>=0) or -1 (error) / -2 (input cap) / -3 (output cap) / -4 (ratio cap).

    Args:
        lib: An open handle to libcompress_mojo.so.
        state: C `*mut GzipState`.
        in_ptr: C `*const u8`.
        in_len: C `usize`.
        out_ptr: C `*mut u8`.
        out_cap: C `usize`.

    Returns:
        C `i64`.

    Raises:
        If `lcm_gzip_feed` is not exported by the loaded library.
    """
    return lib.get_function[Int64]("lcm_gzip_feed")(state, in_ptr, in_len, out_ptr, out_cap)


@always_inline
def call_lcm_gzip_finish(
    ref lib: OwnedDLHandle,
    state: Pointer[mut=True, T=NoneType, origin=_],
    out_ptr: Pointer[mut=True, T=UInt8, origin=_],
    out_cap: Int,
) raises -> Int64:
    """Drain remaining decompressed bytes. Repeatable until it returns 0.

    Args:
        lib: An open handle to libcompress_mojo.so.
        state: C `*mut GzipState`.
        out_ptr: C `*mut u8`.
        out_cap: C `usize`.

    Returns:
        C `i64`.

    Raises:
        If `lcm_gzip_finish` is not exported by the loaded library.
    """
    return lib.get_function[Int64]("lcm_gzip_finish")(state, out_ptr, out_cap)


@always_inline
def call_lcm_gzip_free(
    ref lib: OwnedDLHandle,
    state: Pointer[mut=True, T=NoneType, origin=_],
) raises -> None:
    """Free a GzipState previously returned by lcm_gzip_init.

    Args:
        lib: An open handle to libcompress_mojo.so.
        state: C `*mut GzipState`.

    Raises:
        If `lcm_gzip_free` is not exported by the loaded library.
    """
    lib.get_function[NoneType]("lcm_gzip_free")(state)


@always_inline
def call_lcm_br_init(
    ref lib: OwnedDLHandle,
    input_cap: UInt64,
    output_cap: UInt64,
    ratio_x100: UInt32,
) raises -> Pointer[NoneType, MutUntrackedOrigin]:
    """Allocate a BrotliState with explicit decompression caps. Cap of 0 disables the corresponding check.

    Args:
        lib: An open handle to libcompress_mojo.so.
        input_cap: C `u64`.
        output_cap: C `u64`.
        ratio_x100: C `u32`.

    Returns:
        C `*mut BrotliState`.

    Raises:
        If `lcm_br_init` is not exported by the loaded library.
    """
    return lib.get_function[Pointer[NoneType, MutUntrackedOrigin]]("lcm_br_init")(input_cap, output_cap, ratio_x100)


@always_inline
def call_lcm_br_feed(
    ref lib: OwnedDLHandle,
    state: Pointer[mut=True, T=NoneType, origin=_],
    in_ptr: Pointer[mut=True, T=UInt8, origin=_],
    in_len: Int,
    out_ptr: Pointer[mut=True, T=UInt8, origin=_],
    out_cap: Int,
) raises -> Int64:
    """Feed compressed bytes; write up to out_cap decompressed bytes. Same return contract as lcm_gzip_feed.

    Args:
        lib: An open handle to libcompress_mojo.so.
        state: C `*mut BrotliState`.
        in_ptr: C `*const u8`.
        in_len: C `usize`.
        out_ptr: C `*mut u8`.
        out_cap: C `usize`.

    Returns:
        C `i64`.

    Raises:
        If `lcm_br_feed` is not exported by the loaded library.
    """
    return lib.get_function[Int64]("lcm_br_feed")(state, in_ptr, in_len, out_ptr, out_cap)


@always_inline
def call_lcm_br_finish(
    ref lib: OwnedDLHandle,
    state: Pointer[mut=True, T=NoneType, origin=_],
    out_ptr: Pointer[mut=True, T=UInt8, origin=_],
    out_cap: Int,
) raises -> Int64:
    """Drain remaining decompressed bytes. Repeatable until it returns 0.

    Args:
        lib: An open handle to libcompress_mojo.so.
        state: C `*mut BrotliState`.
        out_ptr: C `*mut u8`.
        out_cap: C `usize`.

    Returns:
        C `i64`.

    Raises:
        If `lcm_br_finish` is not exported by the loaded library.
    """
    return lib.get_function[Int64]("lcm_br_finish")(state, out_ptr, out_cap)


@always_inline
def call_lcm_br_free(
    ref lib: OwnedDLHandle,
    state: Pointer[mut=True, T=NoneType, origin=_],
) raises -> None:
    """Free a BrotliState previously returned by lcm_br_init.

    Args:
        lib: An open handle to libcompress_mojo.so.
        state: C `*mut BrotliState`.

    Raises:
        If `lcm_br_free` is not exported by the loaded library.
    """
    lib.get_function[NoneType]("lcm_br_free")(state)


# -- Raw function-pointer loaders (hot paths only) -------------------------
#
# Each resolves once and hands back a bare C ABI pointer, for a caller
# that measured the per-call `dlsym` and needs to cache the pointer in a
# struct field. Unlike `call_*`, the pointer carries no borrow of the
# handle: it stays valid only while the handle keeps the library loaded,
# which the caller must guarantee. Everywhere else, use `call_*`.

@always_inline
def load_lcm_last_error(ref lib: OwnedDLHandle) raises -> lcm_last_error_fn:
    """Resolve `lcm_last_error` to a raw C ABI function pointer.

    Args:
        lib: An open handle to libcompress_mojo.so.

    Returns:
        The `lcm_last_error` entry point, valid while `lib` stays open.

    Raises:
        If `lcm_last_error` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("lcm_last_error")
    if not sym:
        raise Error("symbol not found: lcm_last_error")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[lcm_last_error_fn]()[]


@always_inline
def load_lcm_gzip_init(ref lib: OwnedDLHandle) raises -> lcm_gzip_init_fn:
    """Resolve `lcm_gzip_init` to a raw C ABI function pointer.

    Args:
        lib: An open handle to libcompress_mojo.so.

    Returns:
        The `lcm_gzip_init` entry point, valid while `lib` stays open.

    Raises:
        If `lcm_gzip_init` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("lcm_gzip_init")
    if not sym:
        raise Error("symbol not found: lcm_gzip_init")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[lcm_gzip_init_fn]()[]


@always_inline
def load_lcm_gzip_feed(ref lib: OwnedDLHandle) raises -> lcm_gzip_feed_fn:
    """Resolve `lcm_gzip_feed` to a raw C ABI function pointer.

    Args:
        lib: An open handle to libcompress_mojo.so.

    Returns:
        The `lcm_gzip_feed` entry point, valid while `lib` stays open.

    Raises:
        If `lcm_gzip_feed` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("lcm_gzip_feed")
    if not sym:
        raise Error("symbol not found: lcm_gzip_feed")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[lcm_gzip_feed_fn]()[]


@always_inline
def load_lcm_gzip_finish(ref lib: OwnedDLHandle) raises -> lcm_gzip_finish_fn:
    """Resolve `lcm_gzip_finish` to a raw C ABI function pointer.

    Args:
        lib: An open handle to libcompress_mojo.so.

    Returns:
        The `lcm_gzip_finish` entry point, valid while `lib` stays open.

    Raises:
        If `lcm_gzip_finish` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("lcm_gzip_finish")
    if not sym:
        raise Error("symbol not found: lcm_gzip_finish")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[lcm_gzip_finish_fn]()[]


@always_inline
def load_lcm_gzip_free(ref lib: OwnedDLHandle) raises -> lcm_gzip_free_fn:
    """Resolve `lcm_gzip_free` to a raw C ABI function pointer.

    Args:
        lib: An open handle to libcompress_mojo.so.

    Returns:
        The `lcm_gzip_free` entry point, valid while `lib` stays open.

    Raises:
        If `lcm_gzip_free` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("lcm_gzip_free")
    if not sym:
        raise Error("symbol not found: lcm_gzip_free")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[lcm_gzip_free_fn]()[]


@always_inline
def load_lcm_br_init(ref lib: OwnedDLHandle) raises -> lcm_br_init_fn:
    """Resolve `lcm_br_init` to a raw C ABI function pointer.

    Args:
        lib: An open handle to libcompress_mojo.so.

    Returns:
        The `lcm_br_init` entry point, valid while `lib` stays open.

    Raises:
        If `lcm_br_init` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("lcm_br_init")
    if not sym:
        raise Error("symbol not found: lcm_br_init")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[lcm_br_init_fn]()[]


@always_inline
def load_lcm_br_feed(ref lib: OwnedDLHandle) raises -> lcm_br_feed_fn:
    """Resolve `lcm_br_feed` to a raw C ABI function pointer.

    Args:
        lib: An open handle to libcompress_mojo.so.

    Returns:
        The `lcm_br_feed` entry point, valid while `lib` stays open.

    Raises:
        If `lcm_br_feed` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("lcm_br_feed")
    if not sym:
        raise Error("symbol not found: lcm_br_feed")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[lcm_br_feed_fn]()[]


@always_inline
def load_lcm_br_finish(ref lib: OwnedDLHandle) raises -> lcm_br_finish_fn:
    """Resolve `lcm_br_finish` to a raw C ABI function pointer.

    Args:
        lib: An open handle to libcompress_mojo.so.

    Returns:
        The `lcm_br_finish` entry point, valid while `lib` stays open.

    Raises:
        If `lcm_br_finish` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("lcm_br_finish")
    if not sym:
        raise Error("symbol not found: lcm_br_finish")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[lcm_br_finish_fn]()[]


@always_inline
def load_lcm_br_free(ref lib: OwnedDLHandle) raises -> lcm_br_free_fn:
    """Resolve `lcm_br_free` to a raw C ABI function pointer.

    Args:
        lib: An open handle to libcompress_mojo.so.

    Returns:
        The `lcm_br_free` entry point, valid while `lib` stays open.

    Raises:
        If `lcm_br_free` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("lcm_br_free")
    if not sym:
        raise Error("symbol not found: lcm_br_free")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[lcm_br_free_fn]()[]
