"""test_h3_udp_server.mojo — smoke test for H3UdpServer bootstrap.

Doesn't require an external H3 client: registers the 50ms periodic
timeout, polls once to consume the timeout CQE, drains pending
submits, and exits. Catches regressions in:

  * H3UdpServer construction (field init order, pbuf_pool alloc,
    msghdr_template wiring)
  * provide_buffers SQE shape
  * submit_recvmsg_multishot SQE shape
  * submit_timeout SQE shape
  * one poll cycle (loop.poll dispatches the timeout CQE through
    on_complete → _handle_timeout → re-arm via PendingSubmit)
  * drain_pending_submits (the re-arm submit is issued via
    submit_timeout against the loop)

Cert + key paths default to `certs/server.crt` / `certs/server.key`
(generated by `scripts/gen_test_certs.sh`).
"""

from std.collections.dict import Dict
from std.memory import UnsafePointer, Span
from std.memory.unsafe_pointer import alloc as _heap_alloc

from boucle.completion import BatchCompletionLoop
from boucle._sys.linux.raw.ctypes import c_void

from navette.h3.h3_udp_server import (
    H3UdpServer,
    drain_pending_submits,
    PBUF_COUNT,
    PBUF_SIZE,
    PBUF_GROUP_ID,
    OP_RECVMSG,
    OP_TIMEOUT,
    OP_PROVIDE_BUF,
)
from navette.http.handler import (
    StreamHandler,
    Request,
    RecvBody,
    ResponseWriter,
    Capabilities,
    StreamError,
)
from navette.io.udp_socket import udp_listener
from navette.quic.trans_param import default_transport_params
from navette.tls.lib import RustlsLibrary
from navette.tls.config import QuicServerConfig

from interop.file_io import read_file


# Stub handler — the smoke test never reaches a request, so all five
# StreamHandler methods are `pass`.
struct StubHandler(StreamHandler):
    def __init__(out self):
        pass

    def __init__(out self, *, deinit take: Self):
        pass

    def on_request(
        mut self, var req: Request, mut body: RecvBody,
        mut resp: ResponseWriter, caps: Capabilities,
    ) raises:
        pass

    def on_body_available(
        mut self, mut body: RecvBody, mut resp: ResponseWriter,
    ) raises:
        pass

    def on_request_end(
        mut self, mut body: RecvBody, mut resp: ResponseWriter,
    ) raises:
        pass

    def on_send_drained(mut self, mut resp: ResponseWriter) raises:
        pass

    def on_reset(mut self, error: StreamError):
        pass


def make_stub_handler() raises -> StubHandler:
    return StubHandler()


def _encode_token(slot_idx: UInt64, op_kind: UInt8) -> UInt64:
    return (slot_idx << 8) | UInt64(op_kind)


def test_h3_udp_server_init_and_tick() raises:
    """Spin the server up far enough to consume one timeout CQE.

    This exercises every io_uring SQE shape the server submits at
    bootstrap, plus the on_complete + on_flush + _handle_timeout +
    drain_pending_submits chain — without requiring a real H3 client.
    """
    # ── 1. TLS setup ────────────────────────────────────────────
    var cert = read_file(String("certs/server.crt"))
    var key = read_file(String("certs/server.key"))
    var lib = RustlsLibrary()
    var config = QuicServerConfig(lib, Span(cert), Span(key))

    # ── 2. UDP listener on ephemeral port ──────────────────────
    var sock = udp_listener(0)  # kernel picks a free port
    print("test_h3_udp_server: bound fd =", Int(sock.raw()))

    # ── 3. Server + io_uring loop ──────────────────────────────
    var tp = default_transport_params()
    var server = H3UdpServer[StubHandler](
        sock^,
        lib^,
        config^,
        tp^,
        make_stub_handler,
    )
    var io = BatchCompletionLoop[H3UdpServer[StubHandler]](
        server^, sq_entries=64,
    )

    # ── 4. Register provided buffers ────────────────────────────
    var provide_token = _encode_token(UInt64(0), OP_PROVIDE_BUF)
    io.provide_buffers(
        io._handler.pbuf_pool, PBUF_SIZE, PBUF_COUNT, PBUF_GROUP_ID,
        UInt16(0), provide_token,
    )

    # ── 5. Submit initial multishot recvmsg ────────────────────
    var msghdr_addr = Int(io._handler.msghdr_template)
    var msghdr_ptr = UnsafePointer[c_void, StaticConstantOrigin](
        unsafe_from_address=msghdr_addr
    )
    var recvmsg_token = _encode_token(UInt64(0), OP_RECVMSG)
    io.submit_recvmsg_multishot(
        io._handler.udp_handle.raw(), msghdr_ptr, PBUF_GROUP_ID, recvmsg_token,
    )
    io._handler.multishot_active = True

    # ── 6. Submit 50ms periodic timeout — this is what wakes us ─
    var ts_addr = Int(io._handler.timeout_ts)
    var ts_ptr = UnsafePointer[c_void, StaticConstantOrigin](
        unsafe_from_address=ts_addr
    )
    io.submit_timeout(ts_ptr, _encode_token(UInt64(0), OP_TIMEOUT))

    # ── 7. One poll cycle — timeout CQE fires after 50ms ───────
    io.poll(wait_nr=1)

    # _handle_timeout enqueued a re-arm PendingSubmit; drain it
    # to verify drain_pending_submits routes it through
    # submit_timeout cleanly (would raise on SQE-shape mismatch).
    drain_pending_submits(io)

    print("PASS: test_h3_udp_server_init_and_tick")


def main() raises:
    test_h3_udp_server_init_and_tick()
