"""Smoke test for H3UdpServer bootstrap (proactor model).

Doesn't require an external H3 client: spins the proactor lifecycle
through wire_context() + start() + one WatchLoop step (consuming the
50ms timer) + flush(), and exits. Catches regressions in:

  * H3UdpServer construction (field init order, Socket wrapping)
  * wire_context() lifecycle call (no-op after send path ported to WatchLoop)
  * start() (UdpSocketState probe, BufferPool + DatagramStream, timer arm)
  * WatchLoop timer submission and expiry
  * flush() (drains recv stream, polls timer, processes timeout)

Cert + key paths default to `certs/server.crt` / `certs/server.key`
(generated by `scripts/gen_test_certs.sh`).
"""

from std.memory import Pointer
from std.collections import Span
from std.memory.alloc import unsafe_alloc as _heap_alloc

from boucle import WatchLoop

from navette.h3.h3_udp_server import H3UdpServer
from navette.http.handler import (
    StreamHandler,
    Request,
    RecvBody,
    ResponseWriter,
    Capabilities,
    StreamError,
)
from navette.runtime.socket_helpers import udp_listener
from navette.quic.trans_param import default_transport_params
from navette.tls.lib import TlsBackend
from navette.tls.config import QuicServerConfig

from interop.file_io import read_file


# Stub handler — the smoke test never reaches a request, so all five
# StreamHandler methods are `pass`.
struct StubHandler(StreamHandler):
    """No-op handler for the bootstrap smoke test."""

    def __init__(out self):
        pass

    def __init__(out self, *, deinit move: Self):
        pass

    def on_request(
        mut self, var req: Request, mut body: RecvBody,
        mut resp: ResponseWriter, caps: Capabilities,
    ) raises:
        pass

    def on_body_available(
        mut self, mut body: RecvBody, mut resp: ResponseWriter,
    ) raises:
        pass

    def on_request_end(
        mut self, mut body: RecvBody, mut resp: ResponseWriter,
    ) raises:
        pass

    def on_send_drained(mut self, mut resp: ResponseWriter) raises:
        pass

    def on_reset(mut self, error: StreamError):
        pass


def make_stub_handler() raises -> StubHandler:
    """Per-conn factory handed to H3UdpServer."""
    return StubHandler()


def test_h3_udp_server_init_and_tick() raises:
    """Spin the server through the full proactor lifecycle.

    Exercises wire_context + start (UdpSocketState probe, BufferPool +
    DatagramStream, timer arm), one WatchLoop step (timer fires after
    50ms), and flush (drains recv stream, polls timer, processes
    timeout, re-arms) without requiring a real H3 client.
    """
    # -- 1. TLS setup --
    var cert = read_file(String("certs/server.crt"))
    var key = read_file(String("certs/server.key"))
    var tls = TlsBackend()
    var config = QuicServerConfig(tls.shared(), Span(cert), Span(key))

    # -- 2. UDP listener on ephemeral port --
    var sock = udp_listener(0)  # kernel picks a free port
    print("test_h3_udp_server: bound fd =", Int(sock.raw()))

    # -- 3. Server construction --
    var tp = default_transport_params()
    var server = H3UdpServer[StubHandler](
        sock^,
        tls^,
        config^,
        tp^,
        make_stub_handler,
    )

    # -- 4. Heap-allocate for pointer stability --
    var srv_ptr = _heap_alloc[H3UdpServer[StubHandler]](1)
    srv_ptr.unsafe_write(server^)

    # -- 5. Lifecycle call (no-op after send path moved to WatchLoop) --
    srv_ptr[].wire_context()

    # -- 6. WatchLoop + start --
    var loop_ptr = _heap_alloc[WatchLoop](1)
    loop_ptr.unsafe_write(WatchLoop(capacity=64))
    srv_ptr[].start(loop_ptr[])

    # -- 7. One WatchLoop step — timer fires after 50ms --
    _ = loop_ptr[].step()

    # -- 8. Flush — polls timer, processes timeout, re-arms, recycles buffers --
    srv_ptr[].flush()

    # -- 9. Teardown --
    _ = srv_ptr.unsafe_take_pointee()
    srv_ptr.unsafe_free()
    _ = loop_ptr.unsafe_take_pointee()
    loop_ptr.unsafe_free()

    print("PASS: test_h3_udp_server_init_and_tick")


def main() raises:
    test_h3_udp_server_init_and_tick()
