#!/usr/bin/env python3
"""§2.3 — emit Mojo bindings from crates/librustls-mojo/symbols.toml.

The schema in symbols.toml is the single source of truth for the rlsm_*
FFI surface. This script emits a Mojo module containing:

  - one `alias <name>_fn = fn(<args>) -> <ret>` per symbol (the
    function-pointer type, importable on its own); and
  - one `fn load_<name>(ref handle: OwnedDLHandle) -> <name>_fn` per
    symbol that resolves the symbol from the handle.

The generated module sits alongside the hand-written
`OwnedDLHandle.call[...]` blocks in src/tls/{lib,config,connection}.mojo
and src/http/decode.mojo. Refactoring those callers to consume the
generated loaders is a separable follow-up.

Type mapping (Rust → Mojo):
    i32                     → Int32
    i64                     → Int64
    u8                      → UInt8
    u32                     → UInt32
    u64                     → UInt64
    usize                   → Int
    *const u8 / *mut u8     → UnsafePointer[UInt8]
    *const i32 / *mut i32   → UnsafePointer[Int32]
    *const u64 / *mut u64   → UnsafePointer[UInt64]
    *const *mut u8          → UnsafePointer[UnsafePointer[UInt8]]
    *mut <opaque struct>    → UnsafePointer[NoneType]
"""
from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path

HEADER = '''# AUTO-GENERATED by scripts/gen_rlsm_bindings.py - DO NOT EDIT BY HAND.
# Source of truth: crates/librustls-mojo/symbols.toml.
# Regenerate via: uv run python scripts/gen_rlsm_bindings.py --out src/tls/_rlsm_bindings.mojo
#
# This module exposes one `alias <name>_fn` per rlsm_* symbol plus a
# `load_<name>(handle)` helper that resolves the symbol from an
# OwnedDLHandle. It sits alongside the hand-written `_handle.call[...]`
# blocks in src/tls/{lib,config,connection}.mojo + src/http/decode.mojo;
# migration to consume these loaders is a follow-up PR (§2.3 of
# plans/2026-05-13-deps-enhancement.md).

from std.ffi import OwnedDLHandle
from std.memory import UnsafePointer
'''


def _ptr_with_origin(mojo_type: str) -> str:
    """Append `, MutAnyOrigin` to a top-level UnsafePointer[T] type.

    Mojo 0.26.2 requires explicit origin on UnsafePointer in function
    parameter signatures. Nested pointers (e.g. UnsafePointer[
    UnsafePointer[UInt8]]) get origin applied at both levels.
    """
    t = mojo_type.strip()
    if t.startswith("UnsafePointer[") and t.endswith("]"):
        inner = t[len("UnsafePointer["):-1].strip()
        # Recurse for nested UnsafePointer (e.g. UnsafePointer[UnsafePointer[UInt8]])
        inner_rendered = _ptr_with_origin(inner) if inner.startswith("UnsafePointer[") else inner
        return f"UnsafePointer[{inner_rendered}, MutAnyOrigin]"
    return t


def render_alias(sym: dict) -> str:
    """`comptime <name>_fn = fn(<args>) -> <ret>` for the symbol.

    Mojo 0.26.2 accepts the new `comptime` keyword for type aliases and
    keeps `fn` as the function-pointer-type spelling. Pointer
    parameters and pointer returns get an explicit `MutAnyOrigin` so
    origin inference does not bite at use sites.
    """
    name = sym["name"]
    margs = [_ptr_with_origin(a) for a in (sym.get("mojo_args") or [])]
    mret = _ptr_with_origin(sym.get("mojo_ret", "Int32"))
    arg_sig = ", ".join(margs)
    return f'comptime {name}_fn = fn({arg_sig}) -> {mret}'


def render_loader(sym: dict) -> str:
    """`fn load_<name>(ref handle: OwnedDLHandle) -> <name>_fn` helper.

    Calls `handle.get_function[<name>_fn]("<name>")`, which is the
    canonical way to resolve a typed function pointer from an
    OwnedDLHandle. The `ref` parameter keeps the handle borrowed.
    """
    name = sym["name"]
    desc = (sym.get("description") or "").strip()
    block = []
    if desc:
        block.append(f'# {desc}')
    block.append(f'fn load_{name}(ref handle: OwnedDLHandle) -> {name}_fn:')
    block.append(
        f'    return handle.get_function[{name}_fn]("{name}")'
    )
    return "\n".join(block)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--schema",
        type=Path,
        default=Path("crates/librustls-mojo/symbols.toml"),
    )
    parser.add_argument(
        "--out",
        type=Path,
        help="output file (default: stdout)",
    )
    args = parser.parse_args(argv)

    if not args.schema.exists():
        print(f"schema not found: {args.schema}", file=sys.stderr)
        return 1

    with args.schema.open("rb") as f:
        doc = tomllib.load(f)

    if doc.get("schema_version") != 1:
        print(
            f"unsupported schema_version: {doc.get('schema_version')}",
            file=sys.stderr,
        )
        return 1

    symbols = doc.get("symbol", [])
    out_parts: list[str] = [HEADER, ""]

    # 1) Function-pointer aliases.
    out_parts.append("# -- Function-pointer aliases ----------------------------------------------")
    out_parts.append("")
    for sym in symbols:
        out_parts.append(render_alias(sym))
    out_parts.append("")

    # 2) Loader helpers.
    out_parts.append("# -- Loader helpers --------------------------------------------------------")
    out_parts.append("")
    for sym in symbols:
        out_parts.append(render_loader(sym))
        out_parts.append("")

    text = "\n".join(out_parts).rstrip() + "\n"

    if args.out:
        args.out.write_text(text)
        print(f"wrote {args.out} ({len(symbols)} symbols)")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
