#!/usr/bin/env python3
"""§2.3 scaffolding — emit Mojo bindings from crates/librustls-mojo/symbols.toml.

Status: skeleton. Generates a header + per-symbol `get_function_unsafe`
declaration. Full migration of all ~50 rlsm_* symbols requires
populating symbols.toml end-to-end and replacing the hand-written
blocks in src/tls/lib.mojo + src/http/decode.mojo with the generated
module. See plans/2026-05-13-deps-enhancement.md §2.3.
"""
from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path

HEADER = '''# AUTO-GENERATED by scripts/gen_rlsm_bindings.py — DO NOT EDIT BY HAND.
# Source of truth: crates/librustls-mojo/symbols.toml.
# Regenerate via: uv run python scripts/gen_rlsm_bindings.py
'''


def render_symbol(sym: dict) -> str:
    name = sym["name"]
    desc = sym.get("description", "").strip()
    margs = sym.get("mojo_args", [])
    mret = sym.get("mojo_ret", "Int32")
    arg_sig = ", ".join(margs)
    fn_type = f"fn({arg_sig}) -> {mret}"
    block = []
    if desc:
        block.append(f"# {desc}")
    block.append(f'var {name} = handle.get_function_unsafe[{fn_type}]("{name}")')
    return "\n".join(block) + "\n"


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--schema", type=Path,
                        default=Path("crates/librustls-mojo/symbols.toml"))
    parser.add_argument("--out", type=Path,
                        help="output file (default: stdout)")
    args = parser.parse_args(argv)

    if not args.schema.exists():
        print(f"schema not found: {args.schema}", file=sys.stderr)
        return 1

    with args.schema.open("rb") as f:
        doc = tomllib.load(f)

    if doc.get("schema_version") != 1:
        print(f"unsupported schema_version: {doc.get('schema_version')}", file=sys.stderr)
        return 1

    out = [HEADER]
    for sym in doc.get("symbol", []):
        out.append(render_symbol(sym))
    text = "\n".join(out)

    if args.out:
        args.out.write_text(text)
        print(f"wrote {args.out} ({len(doc.get('symbol', []))} symbols)")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
