#!/usr/bin/env python3
"""Emit Mojo bindings from a foo-symbols.toml schema.

Generalization of the original gen_rlsm_bindings.py — now takes any
schema path and writes any output path so the same script serves both
librustls-mojo (`rlsm_*`) and libcompress-mojo (`lcm_*`).

For each `[[symbol]]` block in the schema, emits three declarations:

  1. `comptime <name>_fn = def(<args>) abi("C") thin -> <ret>`
     The C ABI spelled out in full. This is the only place the argument
     types live, and both forms below are checked against it.

  2. `def call_<name>(ref lib, <named args>) raises -> <ret>`
     The default way to reach the symbol. Resolves through the public
     `OwnedDLHandle.get_function[<ret>]`, whose returned `_DLCallable`
     borrows the handle for the duration of the call, so the library
     cannot be `dlclose`d between `dlsym` and the call. Mojo 1.0.0
     dropped argument types from `get_function`'s type parameter, so
     the wrapper's own signature is what re-imposes them: a schema
     change moves the wrapper's parameter list and every caller that
     disagrees stops compiling.

  3. `def load_<name>(ref lib) raises -> <name>_fn`
     A raw C ABI function pointer, for hot paths that must resolve once
     and cache the pointer in a struct field instead of paying a `dlsym`
     per call. Still fully argument-typed, because the pointer carries
     `<name>_fn`. Prefer `call_<name>` unless a measurement says
     otherwise: a raw pointer is not tied to the handle's origin, so
     keeping it valid is the caller's responsibility.

Pointer parameters of `call_<name>` are spelled `origin=_`, the
wildcard that infers the caller's own origin. A fixed origin
(`MutAnyOrigin` or `MutUntrackedOrigin`) only accepts pointers already
spelled with that exact origin — Mojo 1.0.0 converts between neither of
them, nor from a tracked `origin_of(x)` — so it would force every caller
holding a Mojo-owned buffer to launder it through `unsafe_origin_cast`,
losing the keep-alive guarantee that stops the buffer being freed before
the FFI call returns. The wildcard accepts all three spellings and
preserves the guarantee for the tracked ones.

Type mapping (Rust/C → Mojo):
    i32                     → Int32
    i64                     → Int64
    u8                      → UInt8
    u32                     → UInt32
    u64                     → UInt64
    usize                   → Int
    void                    → NoneType
    *const u8 / *mut u8     → Pointer[UInt8, <origin>]
    *const i32 / *mut i32   → Pointer[Int32, <origin>]
    *const u64 / *mut u64   → Pointer[UInt64, <origin>]
    *const *mut u8          → Pointer[Pointer[UInt8, MutUntrackedOrigin], <origin>]
    *mut <opaque struct>    → Pointer[NoneType, <origin>]

`<origin>` is `MutUntrackedOrigin` wherever the origin must be concrete
(alias argument types, pointer-to-pointer pointees, C return values) and
the `origin=_` wildcard in a `call_<name>` parameter position.

The schema still spells these as `UnsafePointer[...]`; `UnsafePointer`
is deprecated in Mojo 1.0.0 in favour of the origin-carrying `Pointer`,
so the mapping below rewrites them rather than churning the schema.
"""
from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path

# Origin used for pointers that cannot be generic: the argument types
# baked into a `comptime` function-pointer alias, the pointee of a
# pointer-to-pointer, and any pointer a C function returns. All three
# name memory the C side owns and Mojo does not track.
C_ORIGIN = "MutUntrackedOrigin"


def _header(schema_path: Path, regen_cmd: str, library: str) -> str:
    return f'''# AUTO-GENERATED by scripts/gen_ffi_bindings.py - DO NOT EDIT BY HAND.
# Source of truth: {schema_path}.
# Regenerate via: {regen_cmd}
#
# Three declarations per symbol:
#
#   <name>_fn     the C ABI, spelled in full. The single place the
#                 argument types are written down.
#   call_<name>   the default call form. Public `get_function[<ret>]`,
#                 so the returned callable borrows the handle and the
#                 library cannot be unloaded mid-call. Its own signature
#                 carries the argument types, which `get_function` no
#                 longer does.
#   load_<name>   a raw C ABI function pointer, for a hot path that must
#                 cache the pointer instead of resolving per call. Not
#                 origin-bound: keeping the owning handle alive for as
#                 long as the pointer is the caller's job.
#
# Either call form fails to compile when the schema and the call
# disagree, so drift surfaces as a build error rather than a corrupted
# stack at runtime.

from std.ffi import OwnedDLHandle
from std.memory import Pointer
'''


def _mojo_type(schema_type: str, origin: str) -> str:
    """Render a schema type as a Mojo 1.0.0 type.

    Args:
        schema_type: The `mojo_args` / `mojo_ret` spelling from the schema.
        origin: Origin to give a top-level pointer. Inner pointers always
            get `C_ORIGIN`, since only the outermost one is ever handed a
            Mojo-owned buffer.

    Returns:
        The Mojo type to emit.
    """
    t = schema_type.strip()
    if t == "None":
        return "NoneType"
    for prefix in ("UnsafePointer[", "Pointer["):
        if t.startswith(prefix) and t.endswith("]"):
            inner = t[len(prefix):-1].strip()
            # A nested pointer is a C-side array of C-side pointers.
            return f"Pointer[{_mojo_type(inner, C_ORIGIN)}, {origin}]"
    return t


def _is_pointer(schema_type: str) -> bool:
    """Report whether a schema type is a top-level pointer.

    Args:
        schema_type: The `mojo_args` / `mojo_ret` spelling from the schema.

    Returns:
        True when the type needs an origin.
    """
    t = schema_type.strip()
    return t.startswith("UnsafePointer[") or t.startswith("Pointer[")


def _param_type(schema_type: str) -> str:
    """Render a schema type as a `call_<name>` parameter type.

    A top-level pointer gets the `origin=_` wildcard so the parameter
    accepts a pointer of any mutable origin — tracked ones included,
    which is what keeps a Mojo-owned buffer alive across the FFI call.
    Everything else, including the pointee of a pointer-to-pointer, is
    spelled concretely.

    Args:
        schema_type: The `mojo_args` spelling from the schema.

    Returns:
        The Mojo parameter type to emit.
    """
    if not _is_pointer(schema_type):
        return _mojo_type(schema_type, C_ORIGIN)
    t = schema_type.strip()
    prefix = "UnsafePointer[" if t.startswith("UnsafePointer[") else "Pointer["
    inner = t[len(prefix):-1].strip()
    return f"Pointer[mut=True, T={_mojo_type(inner, C_ORIGIN)}, origin=_]"


def _arg_names(sym: dict) -> list[str]:
    """Return the parameter names for a symbol.

    Args:
        sym: One `[[symbol]]` block.

    Returns:
        `rust_args_names` when the schema supplies one name per argument,
        otherwise positional fallbacks (`a0`, `a1`, ...) so a partially
        annotated schema still generates.
    """
    args = sym.get("mojo_args") or []
    names = sym.get("rust_args_names") or []
    if len(names) == len(args):
        return list(names)
    return [f"a{i}" for i in range(len(args))]


def render_alias(sym: dict) -> str:
    """Render the `comptime <name>_fn` C ABI alias for one symbol.

    Args:
        sym: One `[[symbol]]` block.

    Returns:
        A single-line `comptime` declaration.
    """
    name = sym["name"]
    margs = [_mojo_type(a, C_ORIGIN) for a in (sym.get("mojo_args") or [])]
    mret = _mojo_type(sym.get("mojo_ret", "Int32"), C_ORIGIN)
    return f'comptime {name}_fn = def({", ".join(margs)}) abi("C") thin -> {mret}'


def render_call(sym: dict, library: str) -> str:
    """Render the origin-generic `call_<name>` wrapper for one symbol.

    This is where the schema's argument types are re-imposed on callers,
    which `OwnedDLHandle.get_function` stopped doing in Mojo 1.0.0.

    Args:
        sym: One `[[symbol]]` block.
        library: Shared-object file name, for the docstring.

    Returns:
        The wrapper's source text, without a trailing blank line.
    """
    name = sym["name"]
    desc = (sym.get("description") or "").strip()
    schema_args = sym.get("mojo_args") or []
    rust_args = sym.get("rust_args") or []
    names = _arg_names(sym)
    ret_schema = sym.get("mojo_ret", "Int32")
    is_void = ret_schema.strip() == "None"
    # A void wrapper is declared `-> None`, not `-> NoneType`: the latter is
    # a result type, and Mojo then requires an explicit `return` that a void
    # C call has nothing to produce. `mojo precompile` accepts the mismatch;
    # it only fails once the function is actually emitted.
    ret = "None" if is_void else _mojo_type(ret_schema, C_ORIGIN)
    get_ret = _mojo_type(ret_schema, C_ORIGIN)
    rust_ret = sym.get("rust_ret", "i32")

    params = [f"    {names[i]}: {_param_type(a)}," for i, a in enumerate(schema_args)]

    lines = [
        "@always_inline",
        f"def call_{name}(",
        "    ref lib: OwnedDLHandle,",
    ]
    lines += params
    lines.append(f") raises -> {ret}:")

    doc = ['    """' + (desc if desc else f"Call `{name}`.")]
    doc.append("")
    doc.append("    Args:")
    doc.append(f"        lib: An open handle to {library}.")
    for i, _a in enumerate(schema_args):
        c_type = rust_args[i] if i < len(rust_args) else "?"
        doc.append(f"        {names[i]}: C `{c_type}`.")
    doc.append("")
    if not is_void:
        doc.append("    Returns:")
        doc.append(f"        C `{rust_ret}`.")
        doc.append("")
    doc.append("    Raises:")
    doc.append(f"        If `{name}` is not exported by the loaded library.")
    doc.append('    """')
    lines += doc

    call_args = ", ".join(names)
    body = f'lib.get_function[{get_ret}]("{name}")({call_args})'
    lines.append(f"    {body}" if is_void else f"    return {body}")
    return "\n".join(lines)


def render_loader(sym: dict, library: str) -> str:
    """Render the raw-function-pointer `load_<name>` helper for one symbol.

    Resolution goes through the public `OwnedDLHandle.get_symbol`, then
    reinterprets the symbol's address as a C ABI function pointer — the
    same step `std.ffi` performs internally, done here so the binding
    module depends on no private stdlib API.

    Args:
        sym: One `[[symbol]]` block.
        library: Shared-object file name, for the docstring.

    Returns:
        The helper's source text, without a trailing blank line.
    """
    name = sym["name"]
    return "\n".join([
        "@always_inline",
        f"def load_{name}(ref lib: OwnedDLHandle) raises -> {name}_fn:",
        f'    """Resolve `{name}` to a raw C ABI function pointer.',
        "",
        "    Args:",
        f"        lib: An open handle to {library}.",
        "",
        "    Returns:",
        f"        The `{name}` entry point, valid while `lib` stays open.",
        "",
        "    Raises:",
        f"        If `{name}` is not exported by the loaded library.",
        '    """',
        f'    var sym = lib.get_symbol[NoneType]("{name}")',
        "    if not sym:",
        f'        raise Error("symbol not found: {name}")',
        f"    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[{name}_fn]()[]",
    ])


def _library_name(schema_path: Path) -> str:
    """Infer the shared-object file name a schema describes.

    Args:
        schema_path: Path to `<crate>/symbols.toml`.

    Returns:
        The `.so` file name, e.g. `librustls_mojo.so`.
    """
    return schema_path.parent.name.replace("-", "_") + ".so"


def main(argv: list[str]) -> int:
    """Generate a Mojo binding module from a symbol schema.

    Args:
        argv: Command-line arguments, without the program name.

    Returns:
        Process exit status: 0 on success, 1 on a bad or missing schema.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--schema", type=Path, required=True,
                        help="path to <crate>/symbols.toml")
    parser.add_argument("--out", type=Path,
                        help="output .mojo file (default: stdout)")
    args = parser.parse_args(argv)

    if not args.schema.exists():
        print(f"schema not found: {args.schema}", file=sys.stderr)
        return 1

    with args.schema.open("rb") as f:
        doc = tomllib.load(f)

    if doc.get("schema_version") != 1:
        print(f"unsupported schema_version: {doc.get('schema_version')}", file=sys.stderr)
        return 1

    symbols = doc.get("symbol", [])
    # The generated wrappers take the dlopen handle as `lib`; a schema
    # argument of that name would shadow it and produce a confusing
    # "invalid redefinition" from the Mojo compiler instead of here.
    for sym in symbols:
        if "lib" in _arg_names(sym):
            print(f"{sym['name']}: argument name 'lib' is reserved for the "
                  "library handle; rename it in the schema", file=sys.stderr)
            return 1

    library = _library_name(args.schema)
    out_arg = f"--out {args.out}" if args.out else ""
    regen_cmd = f"uv run python scripts/gen_ffi_bindings.py --schema {args.schema} {out_arg}".rstrip()
    out_parts: list[str] = [_header(args.schema, regen_cmd, library), ""]

    out_parts.append("# -- C ABI function-pointer aliases ----------------------------------------")
    out_parts.append("")
    for sym in symbols:
        out_parts.append(render_alias(sym))
    out_parts.append("")

    out_parts.append("# -- Typed call wrappers ---------------------------------------------------")
    out_parts.append("")
    for sym in symbols:
        out_parts.append(render_call(sym, library))
        out_parts.append("")
        out_parts.append("")

    out_parts.append(
        "# -- Raw function-pointer loaders (hot paths only) -------------------------\n"
        "#\n"
        "# Each resolves once and hands back a bare C ABI pointer, for a caller\n"
        "# that measured the per-call `dlsym` and needs to cache the pointer in a\n"
        "# struct field. Unlike `call_*`, the pointer carries no borrow of the\n"
        "# handle: it stays valid only while the handle keeps the library loaded,\n"
        "# which the caller must guarantee. Everywhere else, use `call_*`."
    )
    out_parts.append("")
    for sym in symbols:
        out_parts.append(render_loader(sym, library))
        out_parts.append("")
        out_parts.append("")

    text = "\n".join(out_parts).rstrip() + "\n"

    if args.out:
        args.out.write_text(text)
        print(f"wrote {args.out} ({len(symbols)} symbols)")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
