#!/usr/bin/env python3
"""Emit Mojo bindings from a foo-symbols.toml schema.

Generalization of the original gen_rlsm_bindings.py — now takes any
schema path and writes any output path so the same script serves both
librustls-mojo (`rlsm_*`) and libcompress-mojo (`lcm_*`).

For each `[[symbol]]` block in the schema, emits:
  - `comptime <name>_fn = fn(<args>) -> <ret>` (function-pointer type)
  - `fn load_<name>(ref handle: OwnedDLHandle) -> <name>_fn`
     (resolves the symbol from a dlopen handle).

Type mapping (Rust → Mojo):
    i32                     → Int32
    i64                     → Int64
    u8                      → UInt8
    u32                     → UInt32
    u64                     → UInt64
    usize                   → Int
    *const u8 / *mut u8     → UnsafePointer[UInt8]
    *const i32 / *mut i32   → UnsafePointer[Int32]
    *const u64 / *mut u64   → UnsafePointer[UInt64]
    *const *mut u8          → UnsafePointer[UnsafePointer[UInt8]]
    *mut <opaque struct>    → UnsafePointer[NoneType]
"""
from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path


def _header(schema_path: Path, regen_cmd: str) -> str:
    return f"""# AUTO-GENERATED by scripts/gen_ffi_bindings.py - DO NOT EDIT BY HAND.
# Source of truth: {schema_path}.
# Regenerate via: {regen_cmd}

from std.ffi import OwnedDLHandle
from std.memory import UnsafePointer
"""


def _ptr_with_origin(mojo_type: str) -> str:
    """Append `, MutAnyOrigin` to a top-level UnsafePointer[T] type."""
    t = mojo_type.strip()
    if t.startswith("UnsafePointer[") and t.endswith("]"):
        inner = t[len("UnsafePointer["):-1].strip()
        inner_rendered = _ptr_with_origin(inner) if inner.startswith("UnsafePointer[") else inner
        return f"UnsafePointer[{inner_rendered}, MutAnyOrigin]"
    return t


def render_alias(sym: dict) -> str:
    name = sym["name"]
    margs = [_ptr_with_origin(a) for a in (sym.get("mojo_args") or [])]
    mret = _ptr_with_origin(sym.get("mojo_ret", "Int32"))
    arg_sig = ", ".join(margs)
    return f'comptime {name}_fn = fn({arg_sig}) -> {mret}'


def render_loader(sym: dict) -> str:
    name = sym["name"]
    desc = (sym.get("description") or "").strip()
    block = []
    if desc:
        block.append(f'# {desc}')
    block.append(f'fn load_{name}(ref handle: OwnedDLHandle) -> {name}_fn:')
    block.append(f'    return handle.get_function[{name}_fn]("{name}")')
    return "\n".join(block)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--schema", type=Path, required=True,
                        help="path to <crate>/symbols.toml")
    parser.add_argument("--out", type=Path,
                        help="output .mojo file (default: stdout)")
    args = parser.parse_args(argv)

    if not args.schema.exists():
        print(f"schema not found: {args.schema}", file=sys.stderr)
        return 1

    with args.schema.open("rb") as f:
        doc = tomllib.load(f)

    if doc.get("schema_version") != 1:
        print(f"unsupported schema_version: {doc.get('schema_version')}", file=sys.stderr)
        return 1

    symbols = doc.get("symbol", [])
    out_arg = f"--out {args.out}" if args.out else ""
    regen_cmd = f"uv run python scripts/gen_ffi_bindings.py --schema {args.schema} {out_arg}".rstrip()
    out_parts: list[str] = [_header(args.schema, regen_cmd), ""]

    out_parts.append("# -- Function-pointer aliases ----------------------------------------------")
    out_parts.append("")
    for sym in symbols:
        out_parts.append(render_alias(sym))
    out_parts.append("")

    out_parts.append("# -- Loader helpers --------------------------------------------------------")
    out_parts.append("")
    for sym in symbols:
        out_parts.append(render_loader(sym))
        out_parts.append("")

    text = "\n".join(out_parts).rstrip() + "\n"

    if args.out:
        args.out.write_text(text)
        print(f"wrote {args.out} ({len(symbols)} symbols)")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
