# AUTO-GENERATED by scripts/gen_ffi_bindings.py - DO NOT EDIT BY HAND.
# Source of truth: crates/librustls-mojo/symbols.toml.
# Regenerate via: uv run python scripts/gen_ffi_bindings.py --schema crates/librustls-mojo/symbols.toml --out navette/tls/_rlsm_bindings.mojo
#
# Three declarations per symbol:
#
#   <name>_fn     the C ABI, spelled in full. The single place the
#                 argument types are written down.
#   call_<name>   the default call form. Public `get_function[<ret>]`,
#                 so the returned callable borrows the handle and the
#                 library cannot be unloaded mid-call. Its own signature
#                 carries the argument types, which `get_function` no
#                 longer does.
#   load_<name>   a raw C ABI function pointer, for a hot path that must
#                 cache the pointer instead of resolving per call. Not
#                 origin-bound: keeping the owning handle alive for as
#                 long as the pointer is the caller's job.
#
# Either call form fails to compile when the schema and the call
# disagree, so drift surfaces as a build error rather than a corrupted
# stack at runtime.

from std.ffi import OwnedDLHandle
from std.memory import Pointer


# -- C ABI function-pointer aliases ----------------------------------------

comptime rlsm_noop_fn = def() abi("C") thin -> Int32
comptime rlsm_last_error_fn = def(Pointer[UInt8, MutUntrackedOrigin], Int32) abi("C") thin -> Int32
comptime rlsm_client_config_new_fn = def() abi("C") thin -> Int32
comptime rlsm_server_config_new_fn = def(Pointer[UInt8, MutUntrackedOrigin], Int32, Pointer[UInt8, MutUntrackedOrigin], Int32) abi("C") thin -> Int32
comptime rlsm_config_free_fn = def(Int32) abi("C") thin -> Int32
comptime rlsm_config_set_alpn_protocols_fn = def(Int32, Pointer[UInt8, MutUntrackedOrigin], Int32) abi("C") thin -> Int32
comptime rlsm_client_config_new_insecure_fn = def() abi("C") thin -> Int32
comptime rlsm_tls_client_new_fn = def(Int32, Pointer[UInt8, MutUntrackedOrigin], Int32) abi("C") thin -> Int32
comptime rlsm_tls_server_new_fn = def(Int32) abi("C") thin -> Int32
comptime rlsm_tls_conn_free_fn = def(Int32) abi("C") thin -> Int32
comptime rlsm_tls_conn_read_tls_fn = def(Int32, Pointer[UInt8, MutUntrackedOrigin], Int32) abi("C") thin -> Int32
comptime rlsm_tls_conn_write_tls_fn = def(Int32, Pointer[UInt8, MutUntrackedOrigin], Int32) abi("C") thin -> Int32
comptime rlsm_tls_conn_read_plaintext_fn = def(Int32, Pointer[UInt8, MutUntrackedOrigin], Int32) abi("C") thin -> Int32
comptime rlsm_tls_conn_write_plaintext_fn = def(Int32, Pointer[UInt8, MutUntrackedOrigin], Int32) abi("C") thin -> Int32
comptime rlsm_tls_conn_is_handshaking_fn = def(Int32) abi("C") thin -> Int32
comptime rlsm_tls_conn_alpn_fn = def(Int32, Pointer[UInt8, MutUntrackedOrigin], Int32) abi("C") thin -> Int32
comptime rlsm_initial_keys_fn = def(Int32, Pointer[UInt8, MutUntrackedOrigin], Int32, Int32) abi("C") thin -> Int32
comptime rlsm_initial_keys_raw_fn = def(Int32, Pointer[UInt8, MutUntrackedOrigin], Int32, Int32, Pointer[UInt8, MutUntrackedOrigin], Pointer[Int32, MutUntrackedOrigin], Pointer[UInt8, MutUntrackedOrigin], Pointer[Int32, MutUntrackedOrigin], Pointer[UInt8, MutUntrackedOrigin], Pointer[Int32, MutUntrackedOrigin]) abi("C") thin -> Int32
comptime rlsm_keys_local_encrypt_fn = def(Int32, UInt64, Pointer[UInt8, MutUntrackedOrigin], Int32, Pointer[UInt8, MutUntrackedOrigin], Int32, Int32) abi("C") thin -> Int32
comptime rlsm_keys_remote_decrypt_fn = def(Int32, UInt64, Pointer[UInt8, MutUntrackedOrigin], Int32, Pointer[UInt8, MutUntrackedOrigin], Int32) abi("C") thin -> Int32
comptime rlsm_keys_local_header_protect_fn = def(Int32, Pointer[UInt8, MutUntrackedOrigin], Int32, Pointer[UInt8, MutUntrackedOrigin], Pointer[UInt8, MutUntrackedOrigin], Int32) abi("C") thin -> Int32
comptime rlsm_keys_remote_header_unprotect_fn = def(Int32, Pointer[UInt8, MutUntrackedOrigin], Int32, Pointer[UInt8, MutUntrackedOrigin], Pointer[UInt8, MutUntrackedOrigin], Int32) abi("C") thin -> Int32
comptime rlsm_keys_batch_header_unprotect_fn = def(Int32, Int32, Pointer[Pointer[UInt8, MutUntrackedOrigin], MutUntrackedOrigin], Pointer[Int32, MutUntrackedOrigin], Pointer[Int32, MutUntrackedOrigin], Pointer[UInt8, MutUntrackedOrigin], Pointer[Int32, MutUntrackedOrigin]) abi("C") thin -> Int32
comptime rlsm_keys_batch_decrypt_fn = def(Int32, Int32, Pointer[UInt64, MutUntrackedOrigin], Pointer[Pointer[UInt8, MutUntrackedOrigin], MutUntrackedOrigin], Pointer[Int32, MutUntrackedOrigin], Pointer[Int32, MutUntrackedOrigin], Pointer[Int32, MutUntrackedOrigin]) abi("C") thin -> Int32
comptime rlsm_keys_batch_header_protect_fn = def(Int32, Int32, Pointer[Pointer[UInt8, MutUntrackedOrigin], MutUntrackedOrigin], Pointer[Int32, MutUntrackedOrigin], Pointer[Int32, MutUntrackedOrigin], Pointer[Int32, MutUntrackedOrigin], Pointer[Int32, MutUntrackedOrigin]) abi("C") thin -> Int32
comptime rlsm_keys_batch_encrypt_fn = def(Int32, Int32, Pointer[UInt64, MutUntrackedOrigin], Pointer[Pointer[UInt8, MutUntrackedOrigin], MutUntrackedOrigin], Pointer[Int32, MutUntrackedOrigin], Pointer[Int32, MutUntrackedOrigin], Pointer[Int32, MutUntrackedOrigin], Pointer[Int32, MutUntrackedOrigin]) abi("C") thin -> Int32
comptime rlsm_keys_tag_len_fn = def(Int32) abi("C") thin -> Int32
comptime rlsm_keys_free_fn = def(Int32) abi("C") thin -> Int32
comptime rlsm_test_keys_free_count_fn = def() abi("C") thin -> UInt64
comptime rlsm_test_keys_free_reset_fn = def() abi("C") thin -> Int32
comptime rlsm_aes_gcm_128_seal_fn = def(Pointer[UInt8, MutUntrackedOrigin], Int32, Pointer[UInt8, MutUntrackedOrigin], Int32, Pointer[UInt8, MutUntrackedOrigin], Int32, Pointer[UInt8, MutUntrackedOrigin], Int32, Pointer[UInt8, MutUntrackedOrigin], Pointer[Int32, MutUntrackedOrigin]) abi("C") thin -> Int32
comptime rlsm_aes_gcm_128_open_fn = def(Pointer[UInt8, MutUntrackedOrigin], Int32, Pointer[UInt8, MutUntrackedOrigin], Int32, Pointer[UInt8, MutUntrackedOrigin], Int32, Pointer[UInt8, MutUntrackedOrigin], Int32, Pointer[UInt8, MutUntrackedOrigin], Pointer[Int32, MutUntrackedOrigin]) abi("C") thin -> Int32
comptime rlsm_hmac_sha256_fn = def(Pointer[UInt8, MutUntrackedOrigin], Int32, Pointer[UInt8, MutUntrackedOrigin], Int32, Pointer[UInt8, MutUntrackedOrigin]) abi("C") thin -> Int32
comptime rlsm_quic_server_config_new_fn = def(Pointer[UInt8, MutUntrackedOrigin], Int32, Pointer[UInt8, MutUntrackedOrigin], Int32, Pointer[UInt8, MutUntrackedOrigin], Int32, UInt32, Pointer[Int32, MutUntrackedOrigin]) abi("C") thin -> Int32
comptime rlsm_quic_client_config_new_fn = def(Pointer[UInt8, MutUntrackedOrigin], Int32, Pointer[Int32, MutUntrackedOrigin]) abi("C") thin -> Int32
comptime rlsm_quic_client_config_new_insecure_fn = def(Pointer[UInt8, MutUntrackedOrigin], Int32, Pointer[Int32, MutUntrackedOrigin]) abi("C") thin -> Int32
comptime rlsm_quic_client_config_with_ca_fn = def(Pointer[UInt8, MutUntrackedOrigin], Int32, Pointer[UInt8, MutUntrackedOrigin], Int32, Pointer[Int32, MutUntrackedOrigin]) abi("C") thin -> Int32
comptime rlsm_quic_client_conn_new_fn = def(Int32, Int32, Pointer[UInt8, MutUntrackedOrigin], Int32, Pointer[UInt8, MutUntrackedOrigin], Int32, Pointer[Int32, MutUntrackedOrigin]) abi("C") thin -> Int32
comptime rlsm_quic_server_conn_new_fn = def(Int32, Int32, Pointer[UInt8, MutUntrackedOrigin], Int32, Pointer[Int32, MutUntrackedOrigin]) abi("C") thin -> Int32
comptime rlsm_quic_conn_free_fn = def(Int32) abi("C") thin -> Int32
comptime rlsm_quic_conn_write_hs_fn = def(Int32, Pointer[UInt8, MutUntrackedOrigin], Int32, Pointer[Int32, MutUntrackedOrigin], Pointer[UInt8, MutUntrackedOrigin]) abi("C") thin -> Int32
comptime rlsm_quic_conn_read_hs_fn = def(Int32, Pointer[UInt8, MutUntrackedOrigin], Int32, Pointer[UInt64, MutUntrackedOrigin], Pointer[UInt64, MutUntrackedOrigin]) abi("C") thin -> Int32
comptime rlsm_quic_conn_alert_fn = def(Int32) abi("C") thin -> Int32
comptime rlsm_quic_conn_take_keys_fn = def(Int32, Pointer[Int32, MutUntrackedOrigin]) abi("C") thin -> Int32
comptime rlsm_quic_conn_take_next_keys_fn = def(Int32, Pointer[Int32, MutUntrackedOrigin]) abi("C") thin -> Int32
comptime rlsm_quic_conn_is_handshaking_fn = def(Int32) abi("C") thin -> Int32
comptime rlsm_quic_conn_handshake_kind_fn = def(Int32) abi("C") thin -> Int32
comptime rlsm_quic_conn_transport_params_fn = def(Int32, Pointer[UInt8, MutUntrackedOrigin], Int32, Pointer[Int32, MutUntrackedOrigin]) abi("C") thin -> Int32
comptime rlsm_quic_conn_alpn_fn = def(Int32, Pointer[UInt8, MutUntrackedOrigin], Int32, Pointer[Int32, MutUntrackedOrigin]) abi("C") thin -> Int32
comptime rlsm_quic_conn_zero_rtt_keys_fn = def(Int32, Pointer[Int32, MutUntrackedOrigin]) abi("C") thin -> Int32
comptime rlsm_quic_server_conn_zero_rtt_keys_fn = def(Int32, Pointer[Int32, MutUntrackedOrigin]) abi("C") thin -> Int32
comptime rlsm_quic_conn_is_early_data_accepted_fn = def(Int32) abi("C") thin -> Int32
comptime rlsm_quic_server_conn_replay_authenticator_fn = def(Int32, Pointer[UInt8, MutUntrackedOrigin], Pointer[UInt, MutUntrackedOrigin]) abi("C") thin -> Int32

# -- Typed call wrappers ---------------------------------------------------

@always_inline
def call_rlsm_noop(
    ref lib: OwnedDLHandle,
) raises -> Int32:
    """Test stub - returns 0.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_noop` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_noop")()


@always_inline
def call_rlsm_last_error(
    ref lib: OwnedDLHandle,
    out_buf: Pointer[mut=True, T=UInt8, origin=_],
    buf_len: Int32,
) raises -> Int32:
    """Copy the last error message into out_buf (NUL-terminated).

    Args:
        lib: An open handle to librustls_mojo.so.
        out_buf: C `*mut u8`.
        buf_len: C `i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_last_error` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_last_error")(out_buf, buf_len)


@always_inline
def call_rlsm_client_config_new(
    ref lib: OwnedDLHandle,
) raises -> Int32:
    """Allocate a default rustls client config (webpki-roots) and return its handle.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_client_config_new` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_client_config_new")()


@always_inline
def call_rlsm_server_config_new(
    ref lib: OwnedDLHandle,
    cert_pem: Pointer[mut=True, T=UInt8, origin=_],
    cert_len: Int32,
    key_pem: Pointer[mut=True, T=UInt8, origin=_],
    key_len: Int32,
) raises -> Int32:
    """Create a TLS server config from PEM cert chain and PEM private key.

    Args:
        lib: An open handle to librustls_mojo.so.
        cert_pem: C `*const u8`.
        cert_len: C `i32`.
        key_pem: C `*const u8`.
        key_len: C `i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_server_config_new` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_server_config_new")(cert_pem, cert_len, key_pem, key_len)


@always_inline
def call_rlsm_config_free(
    ref lib: OwnedDLHandle,
    handle: Int32,
) raises -> Int32:
    """Free a config handle.

    Args:
        lib: An open handle to librustls_mojo.so.
        handle: C `i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_config_free` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_config_free")(handle)


@always_inline
def call_rlsm_config_set_alpn_protocols(
    ref lib: OwnedDLHandle,
    config_handle: Int32,
    protocols: Pointer[mut=True, T=UInt8, origin=_],
    protocols_len: Int32,
) raises -> Int32:
    """Set ALPN wire-encoded protocols on the given config handle.

    Args:
        lib: An open handle to librustls_mojo.so.
        config_handle: C `i32`.
        protocols: C `*const u8`.
        protocols_len: C `i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_config_set_alpn_protocols` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_config_set_alpn_protocols")(config_handle, protocols, protocols_len)


@always_inline
def call_rlsm_client_config_new_insecure(
    ref lib: OwnedDLHandle,
) raises -> Int32:
    """Create a TLS client config accepting any server cert (feature=insecure).

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_client_config_new_insecure` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_client_config_new_insecure")()


@always_inline
def call_rlsm_tls_client_new(
    ref lib: OwnedDLHandle,
    config_handle: Int32,
    server_name_ptr: Pointer[mut=True, T=UInt8, origin=_],
    server_name_len: Int32,
) raises -> Int32:
    """Create a new TLS client connection bound to a config handle.

    Args:
        lib: An open handle to librustls_mojo.so.
        config_handle: C `i32`.
        server_name_ptr: C `*const u8`.
        server_name_len: C `i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_tls_client_new` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_tls_client_new")(config_handle, server_name_ptr, server_name_len)


@always_inline
def call_rlsm_tls_server_new(
    ref lib: OwnedDLHandle,
    config_handle: Int32,
) raises -> Int32:
    """Create a new TLS server connection bound to a config handle.

    Args:
        lib: An open handle to librustls_mojo.so.
        config_handle: C `i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_tls_server_new` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_tls_server_new")(config_handle)


@always_inline
def call_rlsm_tls_conn_free(
    ref lib: OwnedDLHandle,
    handle: Int32,
) raises -> Int32:
    """Free a TLS connection handle.

    Args:
        lib: An open handle to librustls_mojo.so.
        handle: C `i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_tls_conn_free` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_tls_conn_free")(handle)


@always_inline
def call_rlsm_tls_conn_read_tls(
    ref lib: OwnedDLHandle,
    handle: Int32,
    ciphertext_ptr: Pointer[mut=True, T=UInt8, origin=_],
    ct_len: Int32,
) raises -> Int32:
    """Feed ciphertext into the TLS state machine.

    Args:
        lib: An open handle to librustls_mojo.so.
        handle: C `i32`.
        ciphertext_ptr: C `*const u8`.
        ct_len: C `i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_tls_conn_read_tls` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_tls_conn_read_tls")(handle, ciphertext_ptr, ct_len)


@always_inline
def call_rlsm_tls_conn_write_tls(
    ref lib: OwnedDLHandle,
    handle: Int32,
    out_buf: Pointer[mut=True, T=UInt8, origin=_],
    buf_len: Int32,
) raises -> Int32:
    """Drain ciphertext from rustls into out_buf for transmission.

    Args:
        lib: An open handle to librustls_mojo.so.
        handle: C `i32`.
        out_buf: C `*mut u8`.
        buf_len: C `i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_tls_conn_write_tls` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_tls_conn_write_tls")(handle, out_buf, buf_len)


@always_inline
def call_rlsm_tls_conn_read_plaintext(
    ref lib: OwnedDLHandle,
    handle: Int32,
    out_buf: Pointer[mut=True, T=UInt8, origin=_],
    buf_len: Int32,
) raises -> Int32:
    """Read decrypted application data from the TLS connection.

    Args:
        lib: An open handle to librustls_mojo.so.
        handle: C `i32`.
        out_buf: C `*mut u8`.
        buf_len: C `i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_tls_conn_read_plaintext` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_tls_conn_read_plaintext")(handle, out_buf, buf_len)


@always_inline
def call_rlsm_tls_conn_write_plaintext(
    ref lib: OwnedDLHandle,
    handle: Int32,
    data_ptr: Pointer[mut=True, T=UInt8, origin=_],
    data_len: Int32,
) raises -> Int32:
    """Write application data into the TLS connection to be encrypted.

    Args:
        lib: An open handle to librustls_mojo.so.
        handle: C `i32`.
        data_ptr: C `*const u8`.
        data_len: C `i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_tls_conn_write_plaintext` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_tls_conn_write_plaintext")(handle, data_ptr, data_len)


@always_inline
def call_rlsm_tls_conn_is_handshaking(
    ref lib: OwnedDLHandle,
    handle: Int32,
) raises -> Int32:
    """Returns 1 if the TLS handshake is in progress, 0 if complete, -1 on error.

    Args:
        lib: An open handle to librustls_mojo.so.
        handle: C `i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_tls_conn_is_handshaking` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_tls_conn_is_handshaking")(handle)


@always_inline
def call_rlsm_tls_conn_alpn(
    ref lib: OwnedDLHandle,
    handle: Int32,
    out_buf: Pointer[mut=True, T=UInt8, origin=_],
    buf_len: Int32,
) raises -> Int32:
    """Copy negotiated ALPN protocol identifier into out_buf.

    Args:
        lib: An open handle to librustls_mojo.so.
        handle: C `i32`.
        out_buf: C `*mut u8`.
        buf_len: C `i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_tls_conn_alpn` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_tls_conn_alpn")(handle, out_buf, buf_len)


@always_inline
def call_rlsm_initial_keys(
    ref lib: OwnedDLHandle,
    version: Int32,
    dcid_ptr: Pointer[mut=True, T=UInt8, origin=_],
    dcid_len: Int32,
    is_client: Int32,
) raises -> Int32:
    """Derive QUIC Initial keys and return a KEYS_TABLE handle.

    Args:
        lib: An open handle to librustls_mojo.so.
        version: C `i32`.
        dcid_ptr: C `*const u8`.
        dcid_len: C `i32`.
        is_client: C `i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_initial_keys` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_initial_keys")(version, dcid_ptr, dcid_len, is_client)


@always_inline
def call_rlsm_initial_keys_raw(
    ref lib: OwnedDLHandle,
    version: Int32,
    dcid_ptr: Pointer[mut=True, T=UInt8, origin=_],
    dcid_len: Int32,
    is_client: Int32,
    out_key: Pointer[mut=True, T=UInt8, origin=_],
    out_key_len: Pointer[mut=True, T=Int32, origin=_],
    out_iv: Pointer[mut=True, T=UInt8, origin=_],
    out_iv_len: Pointer[mut=True, T=Int32, origin=_],
    out_hp: Pointer[mut=True, T=UInt8, origin=_],
    out_hp_len: Pointer[mut=True, T=Int32, origin=_],
) raises -> Int32:
    """Derive raw QUIC Initial key material (key, IV, HP key).

    Args:
        lib: An open handle to librustls_mojo.so.
        version: C `i32`.
        dcid_ptr: C `*const u8`.
        dcid_len: C `i32`.
        is_client: C `i32`.
        out_key: C `*mut u8`.
        out_key_len: C `*mut i32`.
        out_iv: C `*mut u8`.
        out_iv_len: C `*mut i32`.
        out_hp: C `*mut u8`.
        out_hp_len: C `*mut i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_initial_keys_raw` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_initial_keys_raw")(version, dcid_ptr, dcid_len, is_client, out_key, out_key_len, out_iv, out_iv_len, out_hp, out_hp_len)


@always_inline
def call_rlsm_keys_local_encrypt(
    ref lib: OwnedDLHandle,
    keys_handle: Int32,
    packet_number: UInt64,
    header_ptr: Pointer[mut=True, T=UInt8, origin=_],
    header_len: Int32,
    payload_ptr: Pointer[mut=True, T=UInt8, origin=_],
    payload_len: Int32,
    buf_capacity: Int32,
) raises -> Int32:
    """Encrypt a QUIC packet payload in place using local (sending) keys.

    Args:
        lib: An open handle to librustls_mojo.so.
        keys_handle: C `i32`.
        packet_number: C `u64`.
        header_ptr: C `*const u8`.
        header_len: C `i32`.
        payload_ptr: C `*mut u8`.
        payload_len: C `i32`.
        buf_capacity: C `i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_keys_local_encrypt` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_keys_local_encrypt")(keys_handle, packet_number, header_ptr, header_len, payload_ptr, payload_len, buf_capacity)


@always_inline
def call_rlsm_keys_remote_decrypt(
    ref lib: OwnedDLHandle,
    keys_handle: Int32,
    packet_number: UInt64,
    header_ptr: Pointer[mut=True, T=UInt8, origin=_],
    header_len: Int32,
    payload_ptr: Pointer[mut=True, T=UInt8, origin=_],
    payload_len: Int32,
) raises -> Int32:
    """Decrypt a QUIC packet payload in place using remote (receiving) keys.

    Args:
        lib: An open handle to librustls_mojo.so.
        keys_handle: C `i32`.
        packet_number: C `u64`.
        header_ptr: C `*const u8`.
        header_len: C `i32`.
        payload_ptr: C `*mut u8`.
        payload_len: C `i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_keys_remote_decrypt` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_keys_remote_decrypt")(keys_handle, packet_number, header_ptr, header_len, payload_ptr, payload_len)


@always_inline
def call_rlsm_keys_local_header_protect(
    ref lib: OwnedDLHandle,
    keys_handle: Int32,
    sample_ptr: Pointer[mut=True, T=UInt8, origin=_],
    sample_len: Int32,
    first_byte_ptr: Pointer[mut=True, T=UInt8, origin=_],
    pn_bytes_ptr: Pointer[mut=True, T=UInt8, origin=_],
    pn_len: Int32,
) raises -> Int32:
    """Apply QUIC header protection using local (sending) header keys.

    Args:
        lib: An open handle to librustls_mojo.so.
        keys_handle: C `i32`.
        sample_ptr: C `*const u8`.
        sample_len: C `i32`.
        first_byte_ptr: C `*mut u8`.
        pn_bytes_ptr: C `*mut u8`.
        pn_len: C `i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_keys_local_header_protect` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_keys_local_header_protect")(keys_handle, sample_ptr, sample_len, first_byte_ptr, pn_bytes_ptr, pn_len)


@always_inline
def call_rlsm_keys_remote_header_unprotect(
    ref lib: OwnedDLHandle,
    keys_handle: Int32,
    sample_ptr: Pointer[mut=True, T=UInt8, origin=_],
    sample_len: Int32,
    first_byte_ptr: Pointer[mut=True, T=UInt8, origin=_],
    pn_bytes_ptr: Pointer[mut=True, T=UInt8, origin=_],
    pn_len: Int32,
) raises -> Int32:
    """Remove QUIC header protection using remote (receiving) header keys.

    Args:
        lib: An open handle to librustls_mojo.so.
        keys_handle: C `i32`.
        sample_ptr: C `*const u8`.
        sample_len: C `i32`.
        first_byte_ptr: C `*mut u8`.
        pn_bytes_ptr: C `*mut u8`.
        pn_len: C `i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_keys_remote_header_unprotect` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_keys_remote_header_unprotect")(keys_handle, sample_ptr, sample_len, first_byte_ptr, pn_bytes_ptr, pn_len)


@always_inline
def call_rlsm_keys_batch_header_unprotect(
    ref lib: OwnedDLHandle,
    keys_handle: Int32,
    count: Int32,
    packet_ptrs: Pointer[mut=True, T=Pointer[UInt8, MutUntrackedOrigin], origin=_],
    packet_lens: Pointer[mut=True, T=Int32, origin=_],
    pn_offsets: Pointer[mut=True, T=Int32, origin=_],
    out_first_bytes: Pointer[mut=True, T=UInt8, origin=_],
    out_pn_lengths: Pointer[mut=True, T=Int32, origin=_],
) raises -> Int32:
    """Batch header unprotection for N packets using the same keys.

    Args:
        lib: An open handle to librustls_mojo.so.
        keys_handle: C `i32`.
        count: C `i32`.
        packet_ptrs: C `*const *mut u8`.
        packet_lens: C `*const i32`.
        pn_offsets: C `*const i32`.
        out_first_bytes: C `*mut u8`.
        out_pn_lengths: C `*mut i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_keys_batch_header_unprotect` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_keys_batch_header_unprotect")(keys_handle, count, packet_ptrs, packet_lens, pn_offsets, out_first_bytes, out_pn_lengths)


@always_inline
def call_rlsm_keys_batch_decrypt(
    ref lib: OwnedDLHandle,
    keys_handle: Int32,
    count: Int32,
    packet_numbers: Pointer[mut=True, T=UInt64, origin=_],
    packet_ptrs: Pointer[mut=True, T=Pointer[UInt8, MutUntrackedOrigin], origin=_],
    packet_lens: Pointer[mut=True, T=Int32, origin=_],
    header_lens: Pointer[mut=True, T=Int32, origin=_],
    out_plaintext_lens: Pointer[mut=True, T=Int32, origin=_],
) raises -> Int32:
    """Batch AEAD decryption for N packets using the same keys.

    Args:
        lib: An open handle to librustls_mojo.so.
        keys_handle: C `i32`.
        count: C `i32`.
        packet_numbers: C `*const u64`.
        packet_ptrs: C `*const *mut u8`.
        packet_lens: C `*const i32`.
        header_lens: C `*const i32`.
        out_plaintext_lens: C `*mut i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_keys_batch_decrypt` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_keys_batch_decrypt")(keys_handle, count, packet_numbers, packet_ptrs, packet_lens, header_lens, out_plaintext_lens)


@always_inline
def call_rlsm_keys_batch_header_protect(
    ref lib: OwnedDLHandle,
    keys_handle: Int32,
    count: Int32,
    packet_ptrs: Pointer[mut=True, T=Pointer[UInt8, MutUntrackedOrigin], origin=_],
    packet_lens: Pointer[mut=True, T=Int32, origin=_],
    pn_offsets: Pointer[mut=True, T=Int32, origin=_],
    pn_lengths: Pointer[mut=True, T=Int32, origin=_],
    out_results: Pointer[mut=True, T=Int32, origin=_],
) raises -> Int32:
    """Batch header protection for N packets in the send direction.

    Args:
        lib: An open handle to librustls_mojo.so.
        keys_handle: C `i32`.
        count: C `i32`.
        packet_ptrs: C `*const *mut u8`.
        packet_lens: C `*const i32`.
        pn_offsets: C `*const i32`.
        pn_lengths: C `*const i32`.
        out_results: C `*mut i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_keys_batch_header_protect` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_keys_batch_header_protect")(keys_handle, count, packet_ptrs, packet_lens, pn_offsets, pn_lengths, out_results)


@always_inline
def call_rlsm_keys_batch_encrypt(
    ref lib: OwnedDLHandle,
    keys_handle: Int32,
    count: Int32,
    packet_numbers: Pointer[mut=True, T=UInt64, origin=_],
    packet_ptrs: Pointer[mut=True, T=Pointer[UInt8, MutUntrackedOrigin], origin=_],
    header_lens: Pointer[mut=True, T=Int32, origin=_],
    payload_lens: Pointer[mut=True, T=Int32, origin=_],
    buf_capacities: Pointer[mut=True, T=Int32, origin=_],
    out_ciphertext_lens: Pointer[mut=True, T=Int32, origin=_],
) raises -> Int32:
    """Batch AEAD encryption for N packets in the send direction.

    Args:
        lib: An open handle to librustls_mojo.so.
        keys_handle: C `i32`.
        count: C `i32`.
        packet_numbers: C `*const u64`.
        packet_ptrs: C `*const *mut u8`.
        header_lens: C `*const i32`.
        payload_lens: C `*const i32`.
        buf_capacities: C `*const i32`.
        out_ciphertext_lens: C `*mut i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_keys_batch_encrypt` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_keys_batch_encrypt")(keys_handle, count, packet_numbers, packet_ptrs, header_lens, payload_lens, buf_capacities, out_ciphertext_lens)


@always_inline
def call_rlsm_keys_tag_len(
    ref lib: OwnedDLHandle,
    keys_handle: Int32,
) raises -> Int32:
    """Return the AEAD tag length for the local packet keys, or -1 on error.

    Args:
        lib: An open handle to librustls_mojo.so.
        keys_handle: C `i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_keys_tag_len` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_keys_tag_len")(keys_handle)


@always_inline
def call_rlsm_keys_free(
    ref lib: OwnedDLHandle,
    keys_handle: Int32,
) raises -> Int32:
    """Free a keys handle.

    Args:
        lib: An open handle to librustls_mojo.so.
        keys_handle: C `i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_keys_free` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_keys_free")(keys_handle)


@always_inline
def call_rlsm_test_keys_free_count(
    ref lib: OwnedDLHandle,
) raises -> UInt64:
    """[test-only] Read the number of successful keys_free calls.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        C `u64`.

    Raises:
        If `rlsm_test_keys_free_count` is not exported by the loaded library.
    """
    return lib.get_function[UInt64]("rlsm_test_keys_free_count")()


@always_inline
def call_rlsm_test_keys_free_reset(
    ref lib: OwnedDLHandle,
) raises -> Int32:
    """[test-only] Reset the keys-free counter to zero. Returns 0.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_test_keys_free_reset` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_test_keys_free_reset")()


@always_inline
def call_rlsm_aes_gcm_128_seal(
    ref lib: OwnedDLHandle,
    key_ptr: Pointer[mut=True, T=UInt8, origin=_],
    key_len: Int32,
    nonce_ptr: Pointer[mut=True, T=UInt8, origin=_],
    nonce_len: Int32,
    aad_ptr: Pointer[mut=True, T=UInt8, origin=_],
    aad_len: Int32,
    plaintext_ptr: Pointer[mut=True, T=UInt8, origin=_],
    plaintext_len: Int32,
    out_ptr: Pointer[mut=True, T=UInt8, origin=_],
    out_len_ptr: Pointer[mut=True, T=Int32, origin=_],
) raises -> Int32:
    """Encrypt with raw AES-128-GCM. Output is ciphertext || 16-byte tag.

    Args:
        lib: An open handle to librustls_mojo.so.
        key_ptr: C `*const u8`.
        key_len: C `i32`.
        nonce_ptr: C `*const u8`.
        nonce_len: C `i32`.
        aad_ptr: C `*const u8`.
        aad_len: C `i32`.
        plaintext_ptr: C `*const u8`.
        plaintext_len: C `i32`.
        out_ptr: C `*mut u8`.
        out_len_ptr: C `*mut i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_aes_gcm_128_seal` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_aes_gcm_128_seal")(key_ptr, key_len, nonce_ptr, nonce_len, aad_ptr, aad_len, plaintext_ptr, plaintext_len, out_ptr, out_len_ptr)


@always_inline
def call_rlsm_aes_gcm_128_open(
    ref lib: OwnedDLHandle,
    key_ptr: Pointer[mut=True, T=UInt8, origin=_],
    key_len: Int32,
    nonce_ptr: Pointer[mut=True, T=UInt8, origin=_],
    nonce_len: Int32,
    aad_ptr: Pointer[mut=True, T=UInt8, origin=_],
    aad_len: Int32,
    ciphertext_ptr: Pointer[mut=True, T=UInt8, origin=_],
    ciphertext_len: Int32,
    out_ptr: Pointer[mut=True, T=UInt8, origin=_],
    out_len_ptr: Pointer[mut=True, T=Int32, origin=_],
) raises -> Int32:
    """Decrypt with raw AES-128-GCM. ciphertext includes the 16-byte tag.

    Args:
        lib: An open handle to librustls_mojo.so.
        key_ptr: C `*const u8`.
        key_len: C `i32`.
        nonce_ptr: C `*const u8`.
        nonce_len: C `i32`.
        aad_ptr: C `*const u8`.
        aad_len: C `i32`.
        ciphertext_ptr: C `*const u8`.
        ciphertext_len: C `i32`.
        out_ptr: C `*mut u8`.
        out_len_ptr: C `*mut i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_aes_gcm_128_open` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_aes_gcm_128_open")(key_ptr, key_len, nonce_ptr, nonce_len, aad_ptr, aad_len, ciphertext_ptr, ciphertext_len, out_ptr, out_len_ptr)


@always_inline
def call_rlsm_hmac_sha256(
    ref lib: OwnedDLHandle,
    key_ptr: Pointer[mut=True, T=UInt8, origin=_],
    key_len: Int32,
    msg_ptr: Pointer[mut=True, T=UInt8, origin=_],
    msg_len: Int32,
    out_ptr: Pointer[mut=True, T=UInt8, origin=_],
) raises -> Int32:
    """Compute HMAC-SHA256(key, msg) and write the 32-byte tag to out_ptr.

    Args:
        lib: An open handle to librustls_mojo.so.
        key_ptr: C `*const u8`.
        key_len: C `i32`.
        msg_ptr: C `*const u8`.
        msg_len: C `i32`.
        out_ptr: C `*mut u8`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_hmac_sha256` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_hmac_sha256")(key_ptr, key_len, msg_ptr, msg_len, out_ptr)


@always_inline
def call_rlsm_quic_server_config_new(
    ref lib: OwnedDLHandle,
    cert_pem: Pointer[mut=True, T=UInt8, origin=_],
    cert_len: Int32,
    key_pem: Pointer[mut=True, T=UInt8, origin=_],
    key_len: Int32,
    alpn_ptr: Pointer[mut=True, T=UInt8, origin=_],
    alpn_len: Int32,
    max_early_data: UInt32,
    out_handle: Pointer[mut=True, T=Int32, origin=_],
) raises -> Int32:
    """Create a QUIC server TLS config (TLS 1.3 only) with cert + key + ALPN. max_early_data ∈ {0, 0xFFFFFFFF} (rustls QUIC constraint); any other value is rejected at the FFI boundary.

    Args:
        lib: An open handle to librustls_mojo.so.
        cert_pem: C `*const u8`.
        cert_len: C `i32`.
        key_pem: C `*const u8`.
        key_len: C `i32`.
        alpn_ptr: C `*const u8`.
        alpn_len: C `i32`.
        max_early_data: C `u32`.
        out_handle: C `*mut i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_quic_server_config_new` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_quic_server_config_new")(cert_pem, cert_len, key_pem, key_len, alpn_ptr, alpn_len, max_early_data, out_handle)


@always_inline
def call_rlsm_quic_client_config_new(
    ref lib: OwnedDLHandle,
    alpn_ptr: Pointer[mut=True, T=UInt8, origin=_],
    alpn_len: Int32,
    out_handle: Pointer[mut=True, T=Int32, origin=_],
) raises -> Int32:
    """Create a QUIC client TLS config (TLS 1.3, webpki-roots) with ALPN.

    Args:
        lib: An open handle to librustls_mojo.so.
        alpn_ptr: C `*const u8`.
        alpn_len: C `i32`.
        out_handle: C `*mut i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_quic_client_config_new` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_quic_client_config_new")(alpn_ptr, alpn_len, out_handle)


@always_inline
def call_rlsm_quic_client_config_new_insecure(
    ref lib: OwnedDLHandle,
    alpn_ptr: Pointer[mut=True, T=UInt8, origin=_],
    alpn_len: Int32,
    out_handle: Pointer[mut=True, T=Int32, origin=_],
) raises -> Int32:
    """Create a QUIC client config accepting any server cert (feature=insecure).

    Args:
        lib: An open handle to librustls_mojo.so.
        alpn_ptr: C `*const u8`.
        alpn_len: C `i32`.
        out_handle: C `*mut i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_quic_client_config_new_insecure` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_quic_client_config_new_insecure")(alpn_ptr, alpn_len, out_handle)


@always_inline
def call_rlsm_quic_client_config_with_ca(
    ref lib: OwnedDLHandle,
    ca_pem: Pointer[mut=True, T=UInt8, origin=_],
    ca_len: Int32,
    alpn_ptr: Pointer[mut=True, T=UInt8, origin=_],
    alpn_len: Int32,
    out_handle: Pointer[mut=True, T=Int32, origin=_],
) raises -> Int32:
    """Create a QUIC client config trusting a single CA cert PEM (test helper).

    Args:
        lib: An open handle to librustls_mojo.so.
        ca_pem: C `*const u8`.
        ca_len: C `i32`.
        alpn_ptr: C `*const u8`.
        alpn_len: C `i32`.
        out_handle: C `*mut i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_quic_client_config_with_ca` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_quic_client_config_with_ca")(ca_pem, ca_len, alpn_ptr, alpn_len, out_handle)


@always_inline
def call_rlsm_quic_client_conn_new(
    ref lib: OwnedDLHandle,
    config_handle: Int32,
    version: Int32,
    server_name: Pointer[mut=True, T=UInt8, origin=_],
    name_len: Int32,
    transport_params: Pointer[mut=True, T=UInt8, origin=_],
    tp_len: Int32,
    out_handle: Pointer[mut=True, T=Int32, origin=_],
) raises -> Int32:
    """Create a new QUIC client connection with SNI and transport parameters.

    Args:
        lib: An open handle to librustls_mojo.so.
        config_handle: C `i32`.
        version: C `i32`.
        server_name: C `*const u8`.
        name_len: C `i32`.
        transport_params: C `*const u8`.
        tp_len: C `i32`.
        out_handle: C `*mut i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_quic_client_conn_new` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_quic_client_conn_new")(config_handle, version, server_name, name_len, transport_params, tp_len, out_handle)


@always_inline
def call_rlsm_quic_server_conn_new(
    ref lib: OwnedDLHandle,
    config_handle: Int32,
    version: Int32,
    transport_params: Pointer[mut=True, T=UInt8, origin=_],
    tp_len: Int32,
    out_handle: Pointer[mut=True, T=Int32, origin=_],
) raises -> Int32:
    """Create a new QUIC server connection with transport parameters.

    Args:
        lib: An open handle to librustls_mojo.so.
        config_handle: C `i32`.
        version: C `i32`.
        transport_params: C `*const u8`.
        tp_len: C `i32`.
        out_handle: C `*mut i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_quic_server_conn_new` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_quic_server_conn_new")(config_handle, version, transport_params, tp_len, out_handle)


@always_inline
def call_rlsm_quic_conn_free(
    ref lib: OwnedDLHandle,
    conn_handle: Int32,
) raises -> Int32:
    """Free a QUIC connection handle. Drops any buffered pending key change.

    Args:
        lib: An open handle to librustls_mojo.so.
        conn_handle: C `i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_quic_conn_free` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_quic_conn_free")(conn_handle)


@always_inline
def call_rlsm_quic_conn_write_hs(
    ref lib: OwnedDLHandle,
    conn_handle: Int32,
    out_buf: Pointer[mut=True, T=UInt8, origin=_],
    out_capacity: Int32,
    out_written: Pointer[mut=True, T=Int32, origin=_],
    out_key_change_type: Pointer[mut=True, T=UInt8, origin=_],
) raises -> Int32:
    """Drain outgoing TLS handshake bytes; reports any pending key-change kind.

    Args:
        lib: An open handle to librustls_mojo.so.
        conn_handle: C `i32`.
        out_buf: C `*mut u8`.
        out_capacity: C `i32`.
        out_written: C `*mut i32`.
        out_key_change_type: C `*mut u8`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_quic_conn_write_hs` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_quic_conn_write_hs")(conn_handle, out_buf, out_capacity, out_written, out_key_change_type)


@always_inline
def call_rlsm_quic_conn_read_hs(
    ref lib: OwnedDLHandle,
    conn_handle: Int32,
    data: Pointer[mut=True, T=UInt8, origin=_],
    len: Int32,
    out_state_machine_us: Pointer[mut=True, T=UInt64, origin=_],
    out_handle_lookup_us: Pointer[mut=True, T=UInt64, origin=_],
) raises -> Int32:
    """Feed CRYPTO frame payload into the QUIC TLS state machine.

    Args:
        lib: An open handle to librustls_mojo.so.
        conn_handle: C `i32`.
        data: C `*const u8`.
        len: C `i32`.
        out_state_machine_us: C `*mut u64`.
        out_handle_lookup_us: C `*mut u64`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_quic_conn_read_hs` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_quic_conn_read_hs")(conn_handle, data, len, out_state_machine_us, out_handle_lookup_us)


@always_inline
def call_rlsm_quic_conn_alert(
    ref lib: OwnedDLHandle,
    conn_handle: Int32,
) raises -> Int32:
    """Return the cached TLS AlertDescription code from the last read_hs failure.

    Args:
        lib: An open handle to librustls_mojo.so.
        conn_handle: C `i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_quic_conn_alert` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_quic_conn_alert")(conn_handle)


@always_inline
def call_rlsm_quic_conn_take_keys(
    ref lib: OwnedDLHandle,
    conn_handle: Int32,
    out_keys_handle: Pointer[mut=True, T=Int32, origin=_],
) raises -> Int32:
    """Move the pending QUIC Keys into KEYS_TABLE; returns new keys handle.

    Args:
        lib: An open handle to librustls_mojo.so.
        conn_handle: C `i32`.
        out_keys_handle: C `*mut i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_quic_conn_take_keys` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_quic_conn_take_keys")(conn_handle, out_keys_handle)


@always_inline
def call_rlsm_quic_conn_take_next_keys(
    ref lib: OwnedDLHandle,
    conn_handle: Int32,
    out_keys_handle: Pointer[mut=True, T=Int32, origin=_],
) raises -> Int32:
    """Derive next 1-RTT packet keys from stored Secrets (RFC 9001 §6).

    Args:
        lib: An open handle to librustls_mojo.so.
        conn_handle: C `i32`.
        out_keys_handle: C `*mut i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_quic_conn_take_next_keys` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_quic_conn_take_next_keys")(conn_handle, out_keys_handle)


@always_inline
def call_rlsm_quic_conn_is_handshaking(
    ref lib: OwnedDLHandle,
    conn_handle: Int32,
) raises -> Int32:
    """Returns 1 if handshaking, 0 if complete, -1 on invalid handle.

    Args:
        lib: An open handle to librustls_mojo.so.
        conn_handle: C `i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_quic_conn_is_handshaking` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_quic_conn_is_handshaking")(conn_handle)


@always_inline
def call_rlsm_quic_conn_handshake_kind(
    ref lib: OwnedDLHandle,
    conn_handle: Int32,
) raises -> Int32:
    """Read the handshake kind for a server connection (Full/Resumed/HRR).

    Args:
        lib: An open handle to librustls_mojo.so.
        conn_handle: C `i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_quic_conn_handshake_kind` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_quic_conn_handshake_kind")(conn_handle)


@always_inline
def call_rlsm_quic_conn_transport_params(
    ref lib: OwnedDLHandle,
    conn_handle: Int32,
    out_buf: Pointer[mut=True, T=UInt8, origin=_],
    out_capacity: Int32,
    out_written: Pointer[mut=True, T=Int32, origin=_],
) raises -> Int32:
    """Copy peer's transport parameters into out_buf.

    Args:
        lib: An open handle to librustls_mojo.so.
        conn_handle: C `i32`.
        out_buf: C `*mut u8`.
        out_capacity: C `i32`.
        out_written: C `*mut i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_quic_conn_transport_params` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_quic_conn_transport_params")(conn_handle, out_buf, out_capacity, out_written)


@always_inline
def call_rlsm_quic_conn_alpn(
    ref lib: OwnedDLHandle,
    conn_handle: Int32,
    out_buf: Pointer[mut=True, T=UInt8, origin=_],
    out_capacity: Int32,
    out_written: Pointer[mut=True, T=Int32, origin=_],
) raises -> Int32:
    """Copy negotiated ALPN bytes into out_buf.

    Args:
        lib: An open handle to librustls_mojo.so.
        conn_handle: C `i32`.
        out_buf: C `*mut u8`.
        out_capacity: C `i32`.
        out_written: C `*mut i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_quic_conn_alpn` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_quic_conn_alpn")(conn_handle, out_buf, out_capacity, out_written)


@always_inline
def call_rlsm_quic_conn_zero_rtt_keys(
    ref lib: OwnedDLHandle,
    conn_handle: Int32,
    out_keys_handle: Pointer[mut=True, T=Int32, origin=_],
) raises -> Int32:
    """Write client-side 0-RTT DirectionalKeys into KEYS_TABLE if available.

    Args:
        lib: An open handle to librustls_mojo.so.
        conn_handle: C `i32`.
        out_keys_handle: C `*mut i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_quic_conn_zero_rtt_keys` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_quic_conn_zero_rtt_keys")(conn_handle, out_keys_handle)


@always_inline
def call_rlsm_quic_server_conn_zero_rtt_keys(
    ref lib: OwnedDLHandle,
    conn_handle: Int32,
    out_keys_handle: Pointer[mut=True, T=Int32, origin=_],
) raises -> Int32:
    """Write server-side 0-RTT decrypt DirectionalKeys into KEYS_TABLE if available. Direction-stateless; RFC 9001 §4.1.3 discard is Mojo-side. Returns 0/1/-1 = success/unavailable/error.

    Args:
        lib: An open handle to librustls_mojo.so.
        conn_handle: C `i32`.
        out_keys_handle: C `*mut i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_quic_server_conn_zero_rtt_keys` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_quic_server_conn_zero_rtt_keys")(conn_handle, out_keys_handle)


@always_inline
def call_rlsm_quic_conn_is_early_data_accepted(
    ref lib: OwnedDLHandle,
    conn_handle: Int32,
) raises -> Int32:
    """Returns 1 if server accepted early data (0-RTT), 0 otherwise, -1 on error.

    Args:
        lib: An open handle to librustls_mojo.so.
        conn_handle: C `i32`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_quic_conn_is_early_data_accepted` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_quic_conn_is_early_data_accepted")(conn_handle)


@always_inline
def call_rlsm_quic_server_conn_replay_authenticator(
    ref lib: OwnedDLHandle,
    conn_handle: Int32,
    out_buf: Pointer[mut=True, T=UInt8, origin=_],
    out_len: Pointer[mut=True, T=UInt, origin=_],
) raises -> Int32:
    """Return the 32-byte ClientHello.random captured for this server connection (used as the 0-RTT anti-replay store's dedup key). 0=success, 1=no ClientHello prefix captured yet, -1=invalid handle or client-side connection.

    Args:
        lib: An open handle to librustls_mojo.so.
        conn_handle: C `i32`.
        out_buf: C `*mut u8`.
        out_len: C `*mut usize`.

    Returns:
        C `i32`.

    Raises:
        If `rlsm_quic_server_conn_replay_authenticator` is not exported by the loaded library.
    """
    return lib.get_function[Int32]("rlsm_quic_server_conn_replay_authenticator")(conn_handle, out_buf, out_len)


# -- Raw function-pointer loaders (hot paths only) -------------------------
#
# Each resolves once and hands back a bare C ABI pointer, for a caller
# that measured the per-call `dlsym` and needs to cache the pointer in a
# struct field. Unlike `call_*`, the pointer carries no borrow of the
# handle: it stays valid only while the handle keeps the library loaded,
# which the caller must guarantee. Everywhere else, use `call_*`.

@always_inline
def load_rlsm_noop(ref lib: OwnedDLHandle) raises -> rlsm_noop_fn:
    """Resolve `rlsm_noop` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_noop` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_noop` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_noop")
    if not sym:
        raise Error("symbol not found: rlsm_noop")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_noop_fn]()[]


@always_inline
def load_rlsm_last_error(ref lib: OwnedDLHandle) raises -> rlsm_last_error_fn:
    """Resolve `rlsm_last_error` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_last_error` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_last_error` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_last_error")
    if not sym:
        raise Error("symbol not found: rlsm_last_error")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_last_error_fn]()[]


@always_inline
def load_rlsm_client_config_new(ref lib: OwnedDLHandle) raises -> rlsm_client_config_new_fn:
    """Resolve `rlsm_client_config_new` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_client_config_new` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_client_config_new` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_client_config_new")
    if not sym:
        raise Error("symbol not found: rlsm_client_config_new")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_client_config_new_fn]()[]


@always_inline
def load_rlsm_server_config_new(ref lib: OwnedDLHandle) raises -> rlsm_server_config_new_fn:
    """Resolve `rlsm_server_config_new` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_server_config_new` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_server_config_new` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_server_config_new")
    if not sym:
        raise Error("symbol not found: rlsm_server_config_new")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_server_config_new_fn]()[]


@always_inline
def load_rlsm_config_free(ref lib: OwnedDLHandle) raises -> rlsm_config_free_fn:
    """Resolve `rlsm_config_free` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_config_free` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_config_free` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_config_free")
    if not sym:
        raise Error("symbol not found: rlsm_config_free")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_config_free_fn]()[]


@always_inline
def load_rlsm_config_set_alpn_protocols(ref lib: OwnedDLHandle) raises -> rlsm_config_set_alpn_protocols_fn:
    """Resolve `rlsm_config_set_alpn_protocols` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_config_set_alpn_protocols` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_config_set_alpn_protocols` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_config_set_alpn_protocols")
    if not sym:
        raise Error("symbol not found: rlsm_config_set_alpn_protocols")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_config_set_alpn_protocols_fn]()[]


@always_inline
def load_rlsm_client_config_new_insecure(ref lib: OwnedDLHandle) raises -> rlsm_client_config_new_insecure_fn:
    """Resolve `rlsm_client_config_new_insecure` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_client_config_new_insecure` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_client_config_new_insecure` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_client_config_new_insecure")
    if not sym:
        raise Error("symbol not found: rlsm_client_config_new_insecure")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_client_config_new_insecure_fn]()[]


@always_inline
def load_rlsm_tls_client_new(ref lib: OwnedDLHandle) raises -> rlsm_tls_client_new_fn:
    """Resolve `rlsm_tls_client_new` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_tls_client_new` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_tls_client_new` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_tls_client_new")
    if not sym:
        raise Error("symbol not found: rlsm_tls_client_new")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_tls_client_new_fn]()[]


@always_inline
def load_rlsm_tls_server_new(ref lib: OwnedDLHandle) raises -> rlsm_tls_server_new_fn:
    """Resolve `rlsm_tls_server_new` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_tls_server_new` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_tls_server_new` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_tls_server_new")
    if not sym:
        raise Error("symbol not found: rlsm_tls_server_new")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_tls_server_new_fn]()[]


@always_inline
def load_rlsm_tls_conn_free(ref lib: OwnedDLHandle) raises -> rlsm_tls_conn_free_fn:
    """Resolve `rlsm_tls_conn_free` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_tls_conn_free` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_tls_conn_free` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_tls_conn_free")
    if not sym:
        raise Error("symbol not found: rlsm_tls_conn_free")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_tls_conn_free_fn]()[]


@always_inline
def load_rlsm_tls_conn_read_tls(ref lib: OwnedDLHandle) raises -> rlsm_tls_conn_read_tls_fn:
    """Resolve `rlsm_tls_conn_read_tls` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_tls_conn_read_tls` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_tls_conn_read_tls` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_tls_conn_read_tls")
    if not sym:
        raise Error("symbol not found: rlsm_tls_conn_read_tls")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_tls_conn_read_tls_fn]()[]


@always_inline
def load_rlsm_tls_conn_write_tls(ref lib: OwnedDLHandle) raises -> rlsm_tls_conn_write_tls_fn:
    """Resolve `rlsm_tls_conn_write_tls` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_tls_conn_write_tls` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_tls_conn_write_tls` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_tls_conn_write_tls")
    if not sym:
        raise Error("symbol not found: rlsm_tls_conn_write_tls")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_tls_conn_write_tls_fn]()[]


@always_inline
def load_rlsm_tls_conn_read_plaintext(ref lib: OwnedDLHandle) raises -> rlsm_tls_conn_read_plaintext_fn:
    """Resolve `rlsm_tls_conn_read_plaintext` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_tls_conn_read_plaintext` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_tls_conn_read_plaintext` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_tls_conn_read_plaintext")
    if not sym:
        raise Error("symbol not found: rlsm_tls_conn_read_plaintext")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_tls_conn_read_plaintext_fn]()[]


@always_inline
def load_rlsm_tls_conn_write_plaintext(ref lib: OwnedDLHandle) raises -> rlsm_tls_conn_write_plaintext_fn:
    """Resolve `rlsm_tls_conn_write_plaintext` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_tls_conn_write_plaintext` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_tls_conn_write_plaintext` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_tls_conn_write_plaintext")
    if not sym:
        raise Error("symbol not found: rlsm_tls_conn_write_plaintext")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_tls_conn_write_plaintext_fn]()[]


@always_inline
def load_rlsm_tls_conn_is_handshaking(ref lib: OwnedDLHandle) raises -> rlsm_tls_conn_is_handshaking_fn:
    """Resolve `rlsm_tls_conn_is_handshaking` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_tls_conn_is_handshaking` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_tls_conn_is_handshaking` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_tls_conn_is_handshaking")
    if not sym:
        raise Error("symbol not found: rlsm_tls_conn_is_handshaking")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_tls_conn_is_handshaking_fn]()[]


@always_inline
def load_rlsm_tls_conn_alpn(ref lib: OwnedDLHandle) raises -> rlsm_tls_conn_alpn_fn:
    """Resolve `rlsm_tls_conn_alpn` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_tls_conn_alpn` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_tls_conn_alpn` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_tls_conn_alpn")
    if not sym:
        raise Error("symbol not found: rlsm_tls_conn_alpn")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_tls_conn_alpn_fn]()[]


@always_inline
def load_rlsm_initial_keys(ref lib: OwnedDLHandle) raises -> rlsm_initial_keys_fn:
    """Resolve `rlsm_initial_keys` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_initial_keys` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_initial_keys` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_initial_keys")
    if not sym:
        raise Error("symbol not found: rlsm_initial_keys")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_initial_keys_fn]()[]


@always_inline
def load_rlsm_initial_keys_raw(ref lib: OwnedDLHandle) raises -> rlsm_initial_keys_raw_fn:
    """Resolve `rlsm_initial_keys_raw` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_initial_keys_raw` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_initial_keys_raw` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_initial_keys_raw")
    if not sym:
        raise Error("symbol not found: rlsm_initial_keys_raw")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_initial_keys_raw_fn]()[]


@always_inline
def load_rlsm_keys_local_encrypt(ref lib: OwnedDLHandle) raises -> rlsm_keys_local_encrypt_fn:
    """Resolve `rlsm_keys_local_encrypt` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_keys_local_encrypt` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_keys_local_encrypt` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_keys_local_encrypt")
    if not sym:
        raise Error("symbol not found: rlsm_keys_local_encrypt")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_keys_local_encrypt_fn]()[]


@always_inline
def load_rlsm_keys_remote_decrypt(ref lib: OwnedDLHandle) raises -> rlsm_keys_remote_decrypt_fn:
    """Resolve `rlsm_keys_remote_decrypt` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_keys_remote_decrypt` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_keys_remote_decrypt` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_keys_remote_decrypt")
    if not sym:
        raise Error("symbol not found: rlsm_keys_remote_decrypt")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_keys_remote_decrypt_fn]()[]


@always_inline
def load_rlsm_keys_local_header_protect(ref lib: OwnedDLHandle) raises -> rlsm_keys_local_header_protect_fn:
    """Resolve `rlsm_keys_local_header_protect` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_keys_local_header_protect` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_keys_local_header_protect` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_keys_local_header_protect")
    if not sym:
        raise Error("symbol not found: rlsm_keys_local_header_protect")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_keys_local_header_protect_fn]()[]


@always_inline
def load_rlsm_keys_remote_header_unprotect(ref lib: OwnedDLHandle) raises -> rlsm_keys_remote_header_unprotect_fn:
    """Resolve `rlsm_keys_remote_header_unprotect` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_keys_remote_header_unprotect` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_keys_remote_header_unprotect` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_keys_remote_header_unprotect")
    if not sym:
        raise Error("symbol not found: rlsm_keys_remote_header_unprotect")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_keys_remote_header_unprotect_fn]()[]


@always_inline
def load_rlsm_keys_batch_header_unprotect(ref lib: OwnedDLHandle) raises -> rlsm_keys_batch_header_unprotect_fn:
    """Resolve `rlsm_keys_batch_header_unprotect` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_keys_batch_header_unprotect` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_keys_batch_header_unprotect` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_keys_batch_header_unprotect")
    if not sym:
        raise Error("symbol not found: rlsm_keys_batch_header_unprotect")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_keys_batch_header_unprotect_fn]()[]


@always_inline
def load_rlsm_keys_batch_decrypt(ref lib: OwnedDLHandle) raises -> rlsm_keys_batch_decrypt_fn:
    """Resolve `rlsm_keys_batch_decrypt` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_keys_batch_decrypt` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_keys_batch_decrypt` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_keys_batch_decrypt")
    if not sym:
        raise Error("symbol not found: rlsm_keys_batch_decrypt")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_keys_batch_decrypt_fn]()[]


@always_inline
def load_rlsm_keys_batch_header_protect(ref lib: OwnedDLHandle) raises -> rlsm_keys_batch_header_protect_fn:
    """Resolve `rlsm_keys_batch_header_protect` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_keys_batch_header_protect` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_keys_batch_header_protect` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_keys_batch_header_protect")
    if not sym:
        raise Error("symbol not found: rlsm_keys_batch_header_protect")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_keys_batch_header_protect_fn]()[]


@always_inline
def load_rlsm_keys_batch_encrypt(ref lib: OwnedDLHandle) raises -> rlsm_keys_batch_encrypt_fn:
    """Resolve `rlsm_keys_batch_encrypt` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_keys_batch_encrypt` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_keys_batch_encrypt` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_keys_batch_encrypt")
    if not sym:
        raise Error("symbol not found: rlsm_keys_batch_encrypt")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_keys_batch_encrypt_fn]()[]


@always_inline
def load_rlsm_keys_tag_len(ref lib: OwnedDLHandle) raises -> rlsm_keys_tag_len_fn:
    """Resolve `rlsm_keys_tag_len` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_keys_tag_len` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_keys_tag_len` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_keys_tag_len")
    if not sym:
        raise Error("symbol not found: rlsm_keys_tag_len")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_keys_tag_len_fn]()[]


@always_inline
def load_rlsm_keys_free(ref lib: OwnedDLHandle) raises -> rlsm_keys_free_fn:
    """Resolve `rlsm_keys_free` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_keys_free` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_keys_free` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_keys_free")
    if not sym:
        raise Error("symbol not found: rlsm_keys_free")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_keys_free_fn]()[]


@always_inline
def load_rlsm_test_keys_free_count(ref lib: OwnedDLHandle) raises -> rlsm_test_keys_free_count_fn:
    """Resolve `rlsm_test_keys_free_count` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_test_keys_free_count` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_test_keys_free_count` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_test_keys_free_count")
    if not sym:
        raise Error("symbol not found: rlsm_test_keys_free_count")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_test_keys_free_count_fn]()[]


@always_inline
def load_rlsm_test_keys_free_reset(ref lib: OwnedDLHandle) raises -> rlsm_test_keys_free_reset_fn:
    """Resolve `rlsm_test_keys_free_reset` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_test_keys_free_reset` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_test_keys_free_reset` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_test_keys_free_reset")
    if not sym:
        raise Error("symbol not found: rlsm_test_keys_free_reset")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_test_keys_free_reset_fn]()[]


@always_inline
def load_rlsm_aes_gcm_128_seal(ref lib: OwnedDLHandle) raises -> rlsm_aes_gcm_128_seal_fn:
    """Resolve `rlsm_aes_gcm_128_seal` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_aes_gcm_128_seal` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_aes_gcm_128_seal` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_aes_gcm_128_seal")
    if not sym:
        raise Error("symbol not found: rlsm_aes_gcm_128_seal")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_aes_gcm_128_seal_fn]()[]


@always_inline
def load_rlsm_aes_gcm_128_open(ref lib: OwnedDLHandle) raises -> rlsm_aes_gcm_128_open_fn:
    """Resolve `rlsm_aes_gcm_128_open` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_aes_gcm_128_open` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_aes_gcm_128_open` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_aes_gcm_128_open")
    if not sym:
        raise Error("symbol not found: rlsm_aes_gcm_128_open")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_aes_gcm_128_open_fn]()[]


@always_inline
def load_rlsm_hmac_sha256(ref lib: OwnedDLHandle) raises -> rlsm_hmac_sha256_fn:
    """Resolve `rlsm_hmac_sha256` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_hmac_sha256` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_hmac_sha256` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_hmac_sha256")
    if not sym:
        raise Error("symbol not found: rlsm_hmac_sha256")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_hmac_sha256_fn]()[]


@always_inline
def load_rlsm_quic_server_config_new(ref lib: OwnedDLHandle) raises -> rlsm_quic_server_config_new_fn:
    """Resolve `rlsm_quic_server_config_new` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_quic_server_config_new` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_quic_server_config_new` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_quic_server_config_new")
    if not sym:
        raise Error("symbol not found: rlsm_quic_server_config_new")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_quic_server_config_new_fn]()[]


@always_inline
def load_rlsm_quic_client_config_new(ref lib: OwnedDLHandle) raises -> rlsm_quic_client_config_new_fn:
    """Resolve `rlsm_quic_client_config_new` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_quic_client_config_new` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_quic_client_config_new` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_quic_client_config_new")
    if not sym:
        raise Error("symbol not found: rlsm_quic_client_config_new")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_quic_client_config_new_fn]()[]


@always_inline
def load_rlsm_quic_client_config_new_insecure(ref lib: OwnedDLHandle) raises -> rlsm_quic_client_config_new_insecure_fn:
    """Resolve `rlsm_quic_client_config_new_insecure` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_quic_client_config_new_insecure` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_quic_client_config_new_insecure` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_quic_client_config_new_insecure")
    if not sym:
        raise Error("symbol not found: rlsm_quic_client_config_new_insecure")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_quic_client_config_new_insecure_fn]()[]


@always_inline
def load_rlsm_quic_client_config_with_ca(ref lib: OwnedDLHandle) raises -> rlsm_quic_client_config_with_ca_fn:
    """Resolve `rlsm_quic_client_config_with_ca` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_quic_client_config_with_ca` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_quic_client_config_with_ca` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_quic_client_config_with_ca")
    if not sym:
        raise Error("symbol not found: rlsm_quic_client_config_with_ca")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_quic_client_config_with_ca_fn]()[]


@always_inline
def load_rlsm_quic_client_conn_new(ref lib: OwnedDLHandle) raises -> rlsm_quic_client_conn_new_fn:
    """Resolve `rlsm_quic_client_conn_new` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_quic_client_conn_new` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_quic_client_conn_new` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_quic_client_conn_new")
    if not sym:
        raise Error("symbol not found: rlsm_quic_client_conn_new")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_quic_client_conn_new_fn]()[]


@always_inline
def load_rlsm_quic_server_conn_new(ref lib: OwnedDLHandle) raises -> rlsm_quic_server_conn_new_fn:
    """Resolve `rlsm_quic_server_conn_new` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_quic_server_conn_new` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_quic_server_conn_new` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_quic_server_conn_new")
    if not sym:
        raise Error("symbol not found: rlsm_quic_server_conn_new")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_quic_server_conn_new_fn]()[]


@always_inline
def load_rlsm_quic_conn_free(ref lib: OwnedDLHandle) raises -> rlsm_quic_conn_free_fn:
    """Resolve `rlsm_quic_conn_free` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_quic_conn_free` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_quic_conn_free` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_quic_conn_free")
    if not sym:
        raise Error("symbol not found: rlsm_quic_conn_free")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_quic_conn_free_fn]()[]


@always_inline
def load_rlsm_quic_conn_write_hs(ref lib: OwnedDLHandle) raises -> rlsm_quic_conn_write_hs_fn:
    """Resolve `rlsm_quic_conn_write_hs` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_quic_conn_write_hs` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_quic_conn_write_hs` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_quic_conn_write_hs")
    if not sym:
        raise Error("symbol not found: rlsm_quic_conn_write_hs")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_quic_conn_write_hs_fn]()[]


@always_inline
def load_rlsm_quic_conn_read_hs(ref lib: OwnedDLHandle) raises -> rlsm_quic_conn_read_hs_fn:
    """Resolve `rlsm_quic_conn_read_hs` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_quic_conn_read_hs` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_quic_conn_read_hs` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_quic_conn_read_hs")
    if not sym:
        raise Error("symbol not found: rlsm_quic_conn_read_hs")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_quic_conn_read_hs_fn]()[]


@always_inline
def load_rlsm_quic_conn_alert(ref lib: OwnedDLHandle) raises -> rlsm_quic_conn_alert_fn:
    """Resolve `rlsm_quic_conn_alert` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_quic_conn_alert` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_quic_conn_alert` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_quic_conn_alert")
    if not sym:
        raise Error("symbol not found: rlsm_quic_conn_alert")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_quic_conn_alert_fn]()[]


@always_inline
def load_rlsm_quic_conn_take_keys(ref lib: OwnedDLHandle) raises -> rlsm_quic_conn_take_keys_fn:
    """Resolve `rlsm_quic_conn_take_keys` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_quic_conn_take_keys` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_quic_conn_take_keys` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_quic_conn_take_keys")
    if not sym:
        raise Error("symbol not found: rlsm_quic_conn_take_keys")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_quic_conn_take_keys_fn]()[]


@always_inline
def load_rlsm_quic_conn_take_next_keys(ref lib: OwnedDLHandle) raises -> rlsm_quic_conn_take_next_keys_fn:
    """Resolve `rlsm_quic_conn_take_next_keys` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_quic_conn_take_next_keys` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_quic_conn_take_next_keys` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_quic_conn_take_next_keys")
    if not sym:
        raise Error("symbol not found: rlsm_quic_conn_take_next_keys")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_quic_conn_take_next_keys_fn]()[]


@always_inline
def load_rlsm_quic_conn_is_handshaking(ref lib: OwnedDLHandle) raises -> rlsm_quic_conn_is_handshaking_fn:
    """Resolve `rlsm_quic_conn_is_handshaking` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_quic_conn_is_handshaking` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_quic_conn_is_handshaking` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_quic_conn_is_handshaking")
    if not sym:
        raise Error("symbol not found: rlsm_quic_conn_is_handshaking")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_quic_conn_is_handshaking_fn]()[]


@always_inline
def load_rlsm_quic_conn_handshake_kind(ref lib: OwnedDLHandle) raises -> rlsm_quic_conn_handshake_kind_fn:
    """Resolve `rlsm_quic_conn_handshake_kind` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_quic_conn_handshake_kind` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_quic_conn_handshake_kind` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_quic_conn_handshake_kind")
    if not sym:
        raise Error("symbol not found: rlsm_quic_conn_handshake_kind")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_quic_conn_handshake_kind_fn]()[]


@always_inline
def load_rlsm_quic_conn_transport_params(ref lib: OwnedDLHandle) raises -> rlsm_quic_conn_transport_params_fn:
    """Resolve `rlsm_quic_conn_transport_params` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_quic_conn_transport_params` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_quic_conn_transport_params` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_quic_conn_transport_params")
    if not sym:
        raise Error("symbol not found: rlsm_quic_conn_transport_params")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_quic_conn_transport_params_fn]()[]


@always_inline
def load_rlsm_quic_conn_alpn(ref lib: OwnedDLHandle) raises -> rlsm_quic_conn_alpn_fn:
    """Resolve `rlsm_quic_conn_alpn` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_quic_conn_alpn` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_quic_conn_alpn` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_quic_conn_alpn")
    if not sym:
        raise Error("symbol not found: rlsm_quic_conn_alpn")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_quic_conn_alpn_fn]()[]


@always_inline
def load_rlsm_quic_conn_zero_rtt_keys(ref lib: OwnedDLHandle) raises -> rlsm_quic_conn_zero_rtt_keys_fn:
    """Resolve `rlsm_quic_conn_zero_rtt_keys` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_quic_conn_zero_rtt_keys` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_quic_conn_zero_rtt_keys` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_quic_conn_zero_rtt_keys")
    if not sym:
        raise Error("symbol not found: rlsm_quic_conn_zero_rtt_keys")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_quic_conn_zero_rtt_keys_fn]()[]


@always_inline
def load_rlsm_quic_server_conn_zero_rtt_keys(ref lib: OwnedDLHandle) raises -> rlsm_quic_server_conn_zero_rtt_keys_fn:
    """Resolve `rlsm_quic_server_conn_zero_rtt_keys` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_quic_server_conn_zero_rtt_keys` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_quic_server_conn_zero_rtt_keys` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_quic_server_conn_zero_rtt_keys")
    if not sym:
        raise Error("symbol not found: rlsm_quic_server_conn_zero_rtt_keys")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_quic_server_conn_zero_rtt_keys_fn]()[]


@always_inline
def load_rlsm_quic_conn_is_early_data_accepted(ref lib: OwnedDLHandle) raises -> rlsm_quic_conn_is_early_data_accepted_fn:
    """Resolve `rlsm_quic_conn_is_early_data_accepted` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_quic_conn_is_early_data_accepted` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_quic_conn_is_early_data_accepted` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_quic_conn_is_early_data_accepted")
    if not sym:
        raise Error("symbol not found: rlsm_quic_conn_is_early_data_accepted")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_quic_conn_is_early_data_accepted_fn]()[]


@always_inline
def load_rlsm_quic_server_conn_replay_authenticator(ref lib: OwnedDLHandle) raises -> rlsm_quic_server_conn_replay_authenticator_fn:
    """Resolve `rlsm_quic_server_conn_replay_authenticator` to a raw C ABI function pointer.

    Args:
        lib: An open handle to librustls_mojo.so.

    Returns:
        The `rlsm_quic_server_conn_replay_authenticator` entry point, valid while `lib` stays open.

    Raises:
        If `rlsm_quic_server_conn_replay_authenticator` is not exported by the loaded library.
    """
    var sym = lib.get_symbol[NoneType]("rlsm_quic_server_conn_replay_authenticator")
    if not sym:
        raise Error("symbol not found: rlsm_quic_server_conn_replay_authenticator")
    return Pointer(to=sym.unsafe_value()).unsafe_bitcast[rlsm_quic_server_conn_replay_authenticator_fn]()[]
