[package]
name = "librustls-mojo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rustls = "0.23"
rustls-pemfile = "2"
webpki-roots = "1"

[dev-dependencies]
hex = "0.4"

[features]
default = []
skip-locks = []
insecure = []

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
